### ISSUE TITLE
Prometheus can drop metrics due to Cloudwatch timestamps being too old

### ISSUE THREAD

**Issue by milesbxf** [prometheus/cloudwatch_exporter#100]
Hi @brian-brazil! Thanks for your work on this super-useful project :)

I'm trying to scrape some metrics from S3. As per #38 I ran into issues with time range due to S3 only exposing metrics once a day, so I added `range_seconds: 86400` to ensure they get picked up.

Since #99 added Cloudwatch timestamps, the metric exposed now has an old timestamp that could be anything up to 24 hours old. Consequently I get `msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=1` from Prometheus when I try and scrape the cloudwatch_exporter (off topic but out of interest; what are the semantics Prometheus uses to decide if a sample is "too old" or "too far into the future"?)

Here's the config I'm using:
```
    ---
    region: eu-west-1
    metrics:

    - aws_namespace: AWS/S3
      aws_metric_name: BucketSizeBytes
      aws_dimensions: [BucketName, StorageType]
      aws_dimension_select:
        BucketName: [my-bucket]
        StorageType: [StandardStorage]
      aws_statistics: [Average]
      range_seconds: 86400
```

Ideally I think we'd be able to toggle Cloudwatch timestamps on/off a per-metric basis (perhaps with config like `include_cloudwatch_timestamp: false`). I'm happy to raise a PR if you think it's the best way forward 👍
