### ISSUE TITLE
Adding support for custom labels

### ISSUE THREAD

**Issue by VenkataMutyala** [prometheus/cloudwatch_exporter#103]
I would like to add custom labels to the metrics such that the yaml would look like:

```
---
region: eu-west-1
metrics:
 - aws_namespace: AWS/ELB
   aws_metric_name: RequestCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [myLB]
   aws_statistics: [Sum]
   metric_label:
     key1: value1
     Key2: value2
```
I plan to make this an optional configuration.
