### ISSUE TITLE
Global accesible metrics not being pulled

### ISSUE THREAD

**Issue by Mornor** [prometheus/cloudwatch_exporter#109]
I am trying to pull metrics from our `us-east-1` AWS account in order to pull Cloudfront and Cloudtrail metrics. <br/> 
Per the documentation, [the Region value must be Global](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cf-metricscollected.html) <br/>
However that does not work. From this [thread](https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/issues/4), setting the region to `us-east-1` should solve the issue. However, it did not. <br/>

Here is my configuration file:  

```
region: us-east-1
metrics:
   - aws_namespace: WAF
     aws_metric_name: BlockedRequests
     aws_statistics: [Sum]

   - aws_namespace: AWS/Billing
     aws_dimensions: [Currency]
     aws_dimensions_select:
       Currency: [USD]
     aws_metric_name: EstimatedCharges
     aws_statistics: [Maximum]
     range_seconds: 86400

   - aws_namespace: AWS/CloudFront
     aws_metric_name: Requests
     aws_statistics: [Sum]
     aws_dimensions: [DistributionId]
```

And here is the metrics being scraped

```
curl localhost:9106/metrics
# HELP aws_billing_estimated_charges_maximum CloudWatch metric AWS/Billing EstimatedCharges Dimensions: [Currency] Statistic: Maximum Unit: None
# TYPE aws_billing_estimated_charges_maximum gauge
aws_billing_estimated_charges_maximum{job="aws_billing",instance="",currency="USD",} XXXXXX
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds XXXXXX
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total XXXXX
```

When logged in in the AWS console, the Cloudwatch and Cloudtrail logs are indeed present. 

Do I miss something ? 

PS: It is a duplicate from [here](https://github.com/prometheus/cloudwatch_exporter/issues/93), but unfortunately the ticket has been closed without solution.

**Comment by Mornor** [comment]
Yes indeed: 

```
$> AWS_PROFILE=[profile_name] aws cloudwatch get-metric-statistics --region us-east-1 --metric-name Requests --start-time 2018-06-14T23:18:00Z --end-time 2018-06-18T23:18:00Z --period 3600 --namespace AWS/CloudFront --statistics Sum --dimensions Name=DistributionId,Value=[EXDXXXX] Name=Region,Value=Global

{
    "Label": "Requests",
    "Datapoints": [
        {
            "Timestamp": "2018-06-15T12:18:00Z",
            "Sum": 241.0,
            "Unit": "None"
        },
        {
            "Timestamp": "2018-06-16T21:18:00Z",
            "Sum": 241.0,
            "Unit": "None"
        },
        {
           ........
        }
    ]
}
```

**Comment by Mornor** [comment]
Then the return is empty: 

```
$> env AWS_PROFILE=[profile] aws cloudwatch get-metric-statistics --region us-east-1 --metric-name Requests --start-time 2018-06-14T23:18:00Z --end-time 2018-06-18T23:18:00Z --period 3600 --namespace AWS/CloudFront --statistics Sum --dimensions Name=Region,Value=Global

{
    "Label": "Requests",
    "Datapoints": []
}
```

**Comment by brian-brazil** [comment]
Try it with list-metrics, as that's what the exporter is doing to find the metrics to then get.

**Comment by Mornor** [comment]
Edit: finally made it working with: 
```
- aws_namespace: AWS/CloudFront
   aws_metric_name: Requests
   aws_statistics: [Sum]
   aws_dimensions: [DistributionId, Region]
   aws_dimensions_select:
      Region: [Global]
```

Thanks a lot for your help!

**Comment by brian-brazil** [comment]
Do you want to add that to example.yml, with a comment about the region required?

**Comment by Mornor** [comment]
Sure!
I'll create a pull request today :)

**Comment by eranreshef** [comment]
I am running into a similiar problem, but with WAFV2 instead of CloudFront.
Unfortunately, the above solution does not work for me.
My configuration is:
```
metrics:
  - aws_namespace: AWS/WAFV2
    aws_metric_name: BlockedRequests
    aws_dimensions: [Rule, WebACL, Region]
    aws_dimensions_select:
      Region: [eu-west-1]
```
I am not specifying the `Region` parameter as the exporter is running on an EC2 instance and it should be automatically taken from the instance metadata.
When I call `localhost:9106/metrics` I get all the metrics from other services and:
```
cloudwatch_requests_total{action="listMetrics",namespace="AWS/WAFV2",} 129.0
cloudwatch_requests_total{action="getMetricStatistics",namespace="AWS/WAFV2",} 1753.0
```

without the actual WAF metrics, but when I try with aws-cli
`aws cloudwatch list-metrics --namespace AWS/WAFV2 --metric-name BlockedRequests --dimensions Name=Region,Value=eu-west-1`
 I get the list of all the available metrics that meet these conditions.

What am I doing wrong here?
