### ISSUE TITLE
Issue with AWS Dimension filtering logic

### ISSUE THREAD

**Issue by dbathgate** [prometheus/cloudwatch_exporter#113]
I noticed that not providing `aws_dimensions` and `aws_dimension_select` will filter out all metrics, rather then returning all the metrics by the specified `aws_namespace `/`aws_metric_name`.

Example config:
```yaml
---
region: us-east-1
metrics:
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HealthyHostCount
```

This would return no results for HealthyHostCount.

I found that the exact number of expected AWS dimensions need to be provided in `aws_dimensions` in order for results be returned.

The following does not work:
```yaml
metrics:
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HealthyHostCount
    aws_dimensions: [TargetGroup]
    aws_dimension_select:
      TargetGroup: [targetgroup/mytg/12345]
```

I will however get results if I include both the TargetGroup and LoadBalancer as dimensions.

```yaml
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HealthyHostCount
    aws_dimensions: [TargetGroup, LoadBalancer]
    aws_dimension_select:
      TargetGroup: [targetgroup/mytg/12345]
```

I am wondering if this is by design or an issue int he filtering logic.
I believe I have the filtering logic working in the way I expect so that all 3 of these configurations return results.
