### ISSUE TITLE
Can't get

### ISSUE THREAD

**Issue by vladimir4862** [prometheus/cloudwatch_exporter#114]
Can't get metric: HealthyHostCount in AWS/ApplicationELB 

I can't get metric: HealthyHostCount in namespace AWS/ApplicationELB 
my config:
```

region: eu-west-1
metrics:
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: TargetResponseTime
  aws_dimensions: [LoadBalancer]
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HealthyHostCount
- aws_namespace: AWS/ELB
  aws_metric_name: HealthyHostCount
  aws_statistics: [Sum]
```

 outputs:

> HELP aws_applicationelb_target_response_time_sum CloudWatch metric AWS/ApplicationELB TargetResponseTime Dimensions: [LoadBalancer] Statistic: Sum Unit: Seconds
>  TYPE aws_applicationelb_target_response_time_sum gauge
> aws_applicationelb_target_response_time_sum{job="aws_applicationelb",instance="",load_balancer="app/something",} 18.373832 1529582880000
> aws_applicationelb_target_response_time_sum{job="aws_applicationelb",instance="",load_balancer="app/something",} 0.028957 1529582880000
> aws_applicationelb_target_response_time_sum{job="aws_applicationelb",instance="",load_balancer="app/something",} 0.250251 1529582880000
>  HELP aws_elb_healthy_host_count_sum CloudWatch metric AWS/ELB HealthyHostCount Dimensions: null Statistic: Sum Unit: Count
> TYPE aws_elb_healthy_host_count_sum gauge
> aws_elb_healthy_host_count_sum{job="aws_elb",instance="",} 124.0 1529582880000

```

```
it works for 
```
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_ELB_4XX_Count
```

and works for 
```
- aws_namespace: AWS/ELB
  aws_metric_name: HealthyHostCount
```

and nothing for AWS/ApplicationELB with HealthyHostCount

any advices how i can get this metrics in my cloudwatch_exporter ?
