### ISSUE TITLE
Prometheus is failing to pull metrics from the latest image

### ISSUE THREAD

**Issue by gianrubio** [prometheus/cloudwatch_exporter#115]
Yesterday, one of my Cloudwatch exporter was restarted, and because all the available images are latest, my cluster pulled the image pushed 6 days ago to docker hub. The previous image was running without any issues.

<img width="1014" alt="screen shot 2018-06-25 at 10 36 27" src="https://user-images.githubusercontent.com/5694860/41841586-fc1c315e-7868-11e8-97f3-25e0dfddf905.png">

Since the container restarted Prometheus is complaining about the format of the exporter.

## Prometheus logs

```
time="2018-06-25T08:53:16Z" level=error msg="append failed" err="out of bounds" 
source="scrape.go:518" target="{__address__="10.101.90.4:9100", 
__metrics_path__="/metrics", __scheme__="http", endpoint="0", 
instance="10.101.90.4:9100", job="cloudwatch-exporter", 
namespace="monitoring", pod="cloudwatch-exporter-2869121175-zvctm",
 service="cloudwatch-exporter"}" 
```

## Cloudwatch metrics endpoint

```
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total 1645.0
# HELP aws_rds_free_storage_space_average CloudWatch metric AWS/RDS FreeStorageSpace Dimensions: [DBInstanceIdentifier] Statistic: Average Unit: Bytes
# TYPE aws_rds_free_storage_space_average gauge
aws_rds_free_storage_space_average{job="aws_rds",instance="",dbinstance_identifier="ooo",} 5.7720643584E10 1529914980000
aws_rds_free_storage_space_average{job="aws_rds",instance="",dbinstance_identifier="bbbb",} 2.6073378816E10 1529914980000
# HELP aws_ebs_burst_balance_average CloudWatch metric AWS/EBS BurstBalance Dimensions: [VolumeId] Statistic: Average Unit: Percent
# TYPE aws_ebs_burst_balance_average gauge
aws_ebs_burst_balance_average{job="aws_ebs",instance="",volume_id="vol-2222",} 100.0 1529914800000
# HELP aws_ec2_status_check_failed_average CloudWatch metric AWS/EC2 StatusCheckFailed Dimensions: [InstanceId] Statistic: Average Unit: Count
# TYPE aws_ec2_status_check_failed_average gauge
aws_ec2_status_check_failed_average{job="aws_ec2",instance="",instance_id="i-222",} 0.0 1529914980000
# HELP aws_ec2_status_check_failed_instance_average CloudWatch metric AWS/EC2 StatusCheckFailed_Instance Dimensions: [InstanceId] Statistic: Average Unit: Count
# TYPE aws_ec2_status_check_failed_instance_average gauge
aws_ec2_status_check_failed_instance_average{job="aws_ec2",instance="",instance_id="i-222",} 0.0 1529914980000
# HELP aws_ec2_status_check_failed_system_average CloudWatch metric AWS/EC2 StatusCheckFailed_System Dimensions: [InstanceId] Statistic: Average Unit: Count
# TYPE aws_ec2_status_check_failed_system_average gauge
aws_ec2_status_check_failed_system_average{job="aws_ec2",instance="",instance_id="i-222",} 0.0 1529914980000
# HELP aws_ses_send_sum CloudWatch metric AWS/SES Send Dimensions: null Statistic: Sum Unit: Count
# TYPE aws_ses_send_sum gauge
aws_ses_send_sum{job="aws_ses",instance="",} 1781.0 1529828640000
# HELP aws_ses_delivery_sum CloudWatch metric AWS/SES Delivery Dimensions: null Statistic: Sum Unit: Count
# TYPE aws_ses_delivery_sum gauge
aws_ses_delivery_sum{job="aws_ses",instance="",} 1762.0 1529828640000
# HELP aws_ses_bounce_sum CloudWatch metric AWS/SES Bounce Dimensions: null Statistic: Sum Unit: Count
# TYPE aws_ses_bounce_sum gauge
aws_ses_bounce_sum{job="aws_ses",instance="",} 15.0 1529828640000
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 2.595850326
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
```

Note: Can this project tag images before pushing to docker hub?

**Comment by gianrubio** [comment]
FYI using the release 0.1.0 on [this commit](https://github.com/prometheus/cloudwatch_exporter/commit/8aa4ab117a6934f62c013df50deb6a2d248d30c5) prometheus was able to scrap cloudwatch metrics

**Comment by brian-brazil** [comment]
Can you share your cloudwatch configuration file?

@discordianfish you added the docker image as far as I can tell, how is that getting pushed?

**Comment by gianrubio** [comment]
```
region: eu-west-1
period_seconds: 300
range_seconds: 600
metrics:
- aws_namespace: AWS/RDS
  aws_metric_name: FreeStorageSpace
  aws_dimensions: [DBInstanceIdentifier]
- aws_namespace: AWS/RDS
  aws_metric_name: FreeStorageSpace
  aws_dimensions: [DBInstanceIdentifier]
- aws_namespace: AWS/RDS
  aws_metric_name: WriteLatency
  aws_dimensions: [DBInstanceIdentifier]
- aws_namespace: AWS/RDS
  aws_metric_name: DatabaseConnections
  aws_dimensions: [DBInstanceIdentifier]
- aws_namespace: AWS/EBS
  aws_metric_name: BurstBalance
  aws_dimensions: [VolumeId]
  aws_statistics: [Average]
- aws_namespace: AWS/EC2
  aws_metric_name: StatusCheckFailed
  aws_dimensions: [InstanceId]
  aws_statistics: [Average]
- aws_namespace: AWS/EC2
  aws_metric_name: StatusCheckFailed_Instance
  aws_dimensions: [InstanceId]
  aws_statistics: [Average]
- aws_namespace: AWS/EC2
  aws_metric_name: StatusCheckFailed_System
  aws_dimensions: [InstanceId]
  aws_statistics: [Average]
- aws_namespace: AWS/ELB
  aws_metric_name: UnHealthyHostCount
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Average]
- aws_namespace: AWS/ELB
  aws_metric_name: RequestCount
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Sum]
- aws_namespace: AWS/ELB
  aws_metric_name: Latency
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Average]
```

**Comment by gianrubio** [comment]
Yes it is and ntpd is enabled.

**Comment by brian-brazil** [comment]
And the timestamps being used by the exporter are about 10-15m old?

**Comment by gianrubio** [comment]
I don't think so, as I said before this only happen with the latest image. Rolling back to [this commit](https://github.com/prometheus/cloudwatch_exporter/commit/8aa4ab117a6934f62c013df50deb6a2d248d30c5) fixed the issue.

**Comment by brian-brazil** [comment]
So how old are they then?

**Comment by discordianfish** [comment]
@brian-brazil It's added as automated build on the docker hub: https://hub.docker.com/r/prom/cloudwatch-exporter/builds/

**Comment by ajfriesen** [comment]
I can confirm @gianrubio statement.

* Pulled the code from the commit [8aa4ab117a6934f62c013df50deb6a2d248d30c5](https://github.com/prometheus/cloudwatch_exporter/commit/8aa4ab117a6934f62c013df50deb6a2d248d30c5)
* Build the container on my system
* pushed to my aws registry
* Used the image and tag from my registry

Now metrics collection is working again.

I also would suggest creating tags in docker hub like you do in github.
Otherwise we can not specify images and will have breaking images in production.

**Comment by brian-brazil** [comment]
Can you please tell me how old the timestamps of the data you're seeing are? I can't debug without this information.

> Otherwise we can not specify images and will have breaking images in production.

The official releases are at https://github.com/prometheus/cloudwatch_exporter/releases

**Comment by brian-brazil** [comment]
I'm still waiting to hear how old the timestamps are.

**Comment by sp-joseluis-ledesma** [comment]
we have hit the same issue today. We found that the timestamp sometimes is like 40 minutes old. Also found that cloudwatch-exporter image that is working do not show the timestamp at all(so prometheus may suppose it is the current value)

**Comment by brian-brazil** [comment]
For which metric is that, and can you share your config? With the default settings the data should be no more than 20m old.

**Comment by sp-joseluis-ledesma** [comment]
setting set_timestamp to false solves the issue. As I understand the timestamp on cloudwatch my be somewhat old, so prometheus do not think this is the actual value for the metric

**Comment by sp-joseluis-ledesma** [comment]
this is the config:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: cloudwatch-exporter
  name: cloudwatch-exporter-sqs
  namespace: monitoring
data:
  config.yml: |
    region: us-east-1
    metrics:
    - aws_namespace: AWS/SQS
      aws_metric_name: ApproximateNumberOfMessagesNotVisible
      aws_dimensions: [QueueName]
      aws_statistics: [Maximum]
    - aws_namespace: AWS/SQS
      aws_metric_name: ApproximateNumberOfMessagesVisible
      aws_dimensions: [QueueName]
      aws_statistics: [Maximum]
```

out problem is that we use federation, and the metrics were not scraped (we supose prometheus didn't think the values were the current ones because of the timestamp being to old)
