### ISSUE TITLE
Billing metrics don't end up in Prometheus

### ISSUE THREAD

**Issue by estahn** [prometheus/cloudwatch_exporter#117]
# Problem:
The metrics scraped from `cloudwatch_exporter` can not be found via the prometheus UI. I assume they did not end up in the database.

# Other details:
- We're running helm chart `prometheus-cloudwatch-exporter-0.1.2` with AWS access key/secret
- We're running 2 instances in Kubernetes

```
helm list | grep prometheus-cloudwatch-exporter-0.1.2                                                                                                    
mothy-chinchilla             	25      	Fri Jun 29 19:37:52 2018	DEPLOYED	prometheus-cloudwatch-exporter-0.1.2	devops
super-magician               	9       	Tue Jun  5 14:30:59 2018	DEPLOYED	prometheus-cloudwatch-exporter-0.1.2	devops
```

# Configs
Prometheus config:
```yaml
      # prometheus cloudwatch exporter
      - job_name: 'prometheus-cloudwatch-exporter'
        scrape_timeout: '30s'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__address__]
            target_label: __param_target
            replacement: http://${1}
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: prometheus-cloudwatch-exporter
            action: keep
```

Cloudwatch exporter config:
```
  region: us-east-1
  period_seconds: 3600
  metrics:
    - aws_namespace: AWS/Billing
      aws_metric_name: EstimatedCharges
      aws_dimensions: [ServiceName, LinkedAccount, Currency]
      aws_dimension_select:
        Currency: [USD]
      aws_statistics: [Sum]
      range_seconds: 86400
```

# Tests
Curl in one of the containers:
```
curl http://mothy-chinchilla-prometheus-cloudwatch-exporter.devops.svc:80/metrics
# HELP aws_billing_estimated_charges_sum CloudWatch metric AWS/Billing EstimatedCharges Dimensions: [ServiceName, LinkedAccount, Currency] Statistic: Sum Unit: None
# TYPE aws_billing_estimated_charges_sum gauge
aws_billing_estimated_charges_sum{job="aws_billing",instance="",service_name="AmazonCloudWatch",currency="USD",linked_account="855460960717",} 0.53 1530517260000
...
```

# Scraping
![image](https://user-images.githubusercontent.com/362174/42190798-6f6afef8-7ea2-11e8-80a0-d740a6b4d547.png)
