### ISSUE TITLE
Can't retrieve cloudwatch metrics of other region

### ISSUE THREAD

**Issue by e9d26** [prometheus/cloudwatch_exporter#120]
### The region cloudwatch exporter stands
**ap-northeast-1**

### The region I'd like to retrieve metrics of 
**us-east-1**

### The thing I already succeed
**Retrieve cloudwatch metrics of other region using AWS CLI**
the command I executed is below
`aws cloudwatch list-metrics --namespace "AWS/ApplicationELB" --region us-east-1`

### The thing I failed to do
**Retrieve cloudwatch metrics of other region using cloudwatch exporter**
Here is the config file 
```
---
region: us-east-1
metrics:
 - aws_namespace: "AWS/ApplicationELB"
   aws_metric_name: UnHealthyHostCount
   aws_dimensions: [LoadBalancer,TargetGroup]
   aws_dimension_select_regex:
     LoadBalancer: [.*vir.*]
     TargetGroup: [.*vir.*]
   aws_statistics: [Average]
```

BTW, I tried other region (e.g. eu-central-1, ap-southeast-1), but I failed too.
How come I failed to retrieve cloudwatch metrics of other region ??
Someone please help me.
