### ISSUE TITLE
AWS/EC2 CPUUtilization doesn't work with multiple dimensions

### ISSUE THREAD

**Issue by cristifalcas** [prometheus/cloudwatch_exporter#121]
I can't make AWS/EC2 to work with multiple dimmesnsions.

Those 2 work independently:
```
 - aws_namespace: AWS/EC2
   aws_metric_name: CPUUtilization
   aws_dimensions: [ InstanceId]
# or
 - aws_namespace: AWS/EC2
   aws_metric_name: CPUUtilization
   aws_dimensions: [AutoScalingGroupName]
```
But I can't make them to work together:
```
 - aws_namespace: AWS/EC2
   aws_metric_name: CPUUtilization
   aws_dimensions: [ InstanceId, AutoScalingGroupName]
   aws_dimension_select_regex:
     InstanceId: [".*"]
     AutoScalingGroupName: [".*"]
```

Any known reason for this?
