### ISSUE TITLE
Metrics are not shown in Prometheus query browser.  

### ISSUE THREAD

**Issue by shamimgeek** [prometheus/cloudwatch_exporter#137]
I am not able to see metrics exposed by cloudwatch_exporter except below three metrics. However if i curl to cloudwatch_exporter endpoint it shows all metrics. 

![image](https://user-images.githubusercontent.com/3497115/45627693-c4876800-ba92-11e8-8fcc-0ff9512c4b0a.png)

![image](https://user-images.githubusercontent.com/3497115/45627818-0a443080-ba93-11e8-8042-4c97f44b7289.png)

Can you tell me why i cant see. My configuration is 
```
---
region: eu-central-1
metrics:
# S3 Storage metrics are published to Cloudwatch 1x per day with a timestamp of midnight UTC, hence period_seconds: 86400
# Publishing does not always occur at the same time, but it will occur before the next day, hence range_seconds: 172800
- aws_namespace: AWS/S3
  aws_metric_name: BucketSizeBytes
  aws_dimensions: [BucketName, StorageType]
  aws_statistics: [Average] # Valid statistics (https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html): Average
  range_seconds: 172800
  period_seconds: 86400

- aws_namespace: AWS/S3
  aws_metric_name: NumberOfObjects
  aws_dimensions: [BucketName, StorageType]
  aws_statistics: [Average] # Valid statistics (https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html): Average
  range_seconds: 172800
  period_seconds: 86400
```
Prometheus Configuration:
```
  # Scrape AWS service
  - job_name: cloudwatch_exporter
    scrape_interval: 60s
    scrape_timeout:  30s
    metrics_path: "/metrics"
    static_configs:
    - targets: ['cloudwatchexporter-monitoring.marathon.mesos:9106']
      labels:
        service: cloudwatch_exporter
```
