### ISSUE TITLE
HealthyHostCount and UnHealthyHostCount stats not coming through

### ISSUE THREAD

**Issue by HenryKeen** [prometheus/cloudwatch_exporter#138]
Hi, this is probably a user error but I'm wondering if you might be able to help.

I'm trying to scrape the HealthyHostCount and UnHealthyHostCount metrics but nothing is coming through. My config is:
```
---
region: eu-west-1
metrics:

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: RequestCount
    aws_dimensions: [AvailabilityZone, LoadBalancer]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HealthyHostCount
    aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
    period_seconds: 3600

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: UnHealthyHostCount
    aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
    period_seconds: 3600

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_2XX_Count
    aws_dimensions: [AvailabilityZone, LoadBalancer]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_3XX_Count
    aws_dimensions: [AvailabilityZone, LoadBalancer]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_4XX_Count
    aws_dimensions: [AvailabilityZone, LoadBalancer]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_5XX_Count
    aws_dimensions: [AvailabilityZone, LoadBalancer]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: TargetResponseTime
    aws_dimensions: [AvailabilityZone, LoadBalancer]
```

All the other metrics are coming through fine and I'm seeing no errors logged to console. My user has Admin permissions for this account so full access to the Cloudwatch metrics. I can see the UnHealthyHostCount and HealthyHostCount metrics from the AWS console.

I'm struggling to find ways to debug this, do you have any suggestions? Is there something wrong with my config?
