### ISSUE TITLE
Unexpected results for `aws_applicationelb_httpcode_elb_5_xx_count_sum`

### ISSUE THREAD

**Issue by vkatsikaros** [prometheus/cloudwatch_exporter#152]
Hi

As expected in the prometheus server, if I query for `aws_applicationelb_request_count_sum` I see a long list with all the application load balancers the prometheus server can discover.
![request_count](https://user-images.githubusercontent.com/1138992/47911975-b1442680-de9f-11e8-9d79-8d601b2162b3.png)

However, when I query for `aws_applicationelb_httpcode_elb_5_xx_count_sum` I only see results from 1 load balancer. I would expect to see again as above a long list.
![5xx](https://user-images.githubusercontent.com/1138992/47911985-b73a0780-de9f-11e8-91af-eb3baace746e.png)

I see the same difference if I GET the metrics directly from the exporter
```
$ curl -s 127.0.0.1:9123/metrics | egrep -v "^#" | grep -c aws_applicationelb_httpcode_target_5_xx_count_sum
4
$ curl -s 127.0.0.1:9123/metrics | egrep -v "^#" | grep -c aws_applicationelb_request_count_sum
35
```

I am wondering if I have a configuration error or I miss something from my prom query.

I have configured  the cloudwatch exporter with:
```
---
region: eu-west-2
metrics:
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: RequestCount
  aws_dimensions: [AvailabilityZone, LoadBalancer]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: TargetResponseTime
  aws_dimensions: [AvailabilityZone, LoadBalancer]
  aws_statistics: [Average]
  aws_extended_statistics: [p90.00, p95.00, p99.00]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_ELB_5XX_Count
  aws_dimensions: [AvailabilityZone, LoadBalancer]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_ELB_4XX_Count
  aws_dimensions: [AvailabilityZone, LoadBalancer]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_5XX_Count
  aws_dimensions: [AvailabilityZone, LoadBalancer]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_4XX_Count
  aws_dimensions: [AvailabilityZone, LoadBalancer]
  aws_statistics: [Sum]
```
and the prometheus server with 
```
global:
  scrape_interval: 15s
  external_labels:
    environment: live

scrape_configs:
- job_name: aws_cloudwatch

  ec2_sd_configs:
  - region: eu-west-2
    port: 9123

  relabel_configs:
  - source_labels: [__meta_ec2_tag_role]
    regex: monitoring
    action: keep
  - source_labels: [__meta_ec2_tag_environment]
    regex: live
    action: keep
  - source_labels: [__meta_ec2_private_ip]
    target_label: instance

```

Edit: I added curl commands
