### ISSUE TITLE
CloudSearch metrics

### ISSUE THREAD

**Issue by DraganRaicici** [prometheus/cloudwatch_exporter#158]
Hi there, 
We're having some trouble with configuring the exporter.

Is it not possible to export cloudsearch metrics?

We have filled in the values as described by AWS docs and we still no metrics appearing:
``` 
-aws_namespace: AWS/CloudSearch
   aws_metric_name: SearchableDocuments
   aws_dimensions: [DomainName, ClientId]
   aws_dimension_select:
     DomainName: [ourCloudSearchDomain]
     ClientId: [ourClientId]
   aws_statistics: [Maximum] 
```

Docs found here: https://docs.aws.amazon.com/cloudsearch/latest/developerguide/cloudwatch-monitoring.html
