### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException

### ISSUE THREAD

**Issue by transient1** [prometheus/cloudwatch_exporter#167]
Have the following log in Cloudwatch-exporter pod
`Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at io.prometheus.cloudwatch.CloudWatchCollector.loadConfig(CloudWatchCollector.java:177)
	at io.prometheus.cloudwatch.CloudWatchCollector.loadConfig(CloudWatchCollector.java:96)
	at io.prometheus.cloudwatch.CloudWatchCollector.<init>(CloudWatchCollector.java:74)
	at io.prometheus.cloudwatch.WebServer.main(WebServer.java:25)`

My cloudwatch-config file

```
apiVersion: v1
data:
  config: |
    ---
    region: us-east-1
    metrics:
    - aws_namespace: AWS/RDS
      aws_metric_name: CPUUtilization
      aws_dimensions: [DBInstanceIdentifier]
      aws_dimension_select:
        DBInstanceIdentifier: ['prd-main1', 'prd-main2']
      aws_statistics: [Average]
      period_seconds: 120s

      - aws_namespace: AWS/RDS
      aws_metric_name: WriteLatency
      aws_dimensions: [DBInstanceIdentifier]
      aws_dimension_select:
        DBInstanceIdentifier: ['prd-main1', 'prd-main2']
      aws_statistics: [Average]
      period_seconds: 120s
```

and so on...

This is Kubernetes 1.10 and Prometheus 2.5.0. I copied this over from a previous installation of K8s 1.5 and Prom 1.7.1, where it's working.
