### ISSUE TITLE
Optimal solution for reducing GetMetricStatistics requests?

### ISSUE THREAD

**Issue by andy-han** [prometheus/cloudwatch_exporter#178]
What is the recommended solution for reducing Cloudwatch API calls? Currently when scraping the following metrics, we are getting over 4 Million requests over ~2 days which is really expensive

```
- aws_namespace: AWS/SQS
    aws_metric_name: ApproximateAgeOfOldestMessage
    aws_dimensions: [QueueName]
    aws_statistics: [Average, Maximum]
  - aws_namespace: AWS/SQS
    aws_metric_name: NumberOfMessagesDeleted
    aws_dimensions: [QueueName]
    aws_statistics: [Sum]
  - aws_namespace: AWS/SQS
    aws_metric_name: NumberOfMessagesSent
    aws_dimensions: [QueueName]
    aws_statistics: [Sum, Average]
  - aws_namespace: AWS/SQS
    aws_metric_name: ApproximateNumberOfMessagesVisible
    aws_dimensions: [QueueName]
    aws_statistics: [Sum]
  - aws_namespace: AWS/SNS
    aws_metric_name: NumberOfMessagesPublished
    aws_dimensions: [TopicName]
    aws_statistics: [Sum]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HealthyHostCount
    aws_dimensions: [TargetGroup, LoadBalancer]
    aws_statistics: [Average]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: UnHealthyHostCount
    aws_dimensions: [TargetGroup, LoadBalancer]
    aws_statistics: [Average]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: TargetConnectionErrorCount
    aws_dimensions: [TargetGroup, LoadBalancer]
    aws_statistics: [Sum]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: TargetResponseTime
    aws_dimensions: [TargetGroup, LoadBalancer]
    aws_statistics: [Average]
    aws_extended_statistics: [p75, p90, p95]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: RequestCount
    aws_dimensions: [LoadBalancer]
    aws_statistics: [Sum]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_ELB_4XX_Count
    aws_dimensions: [LoadBalancer]
    aws_statistics: [Sum]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_ELB_5XX_Count
    aws_dimensions: [LoadBalancer]
    aws_statistics: [Sum]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_2XX_Count
    aws_dimensions: [TargetGroup, LoadBalancer]
    aws_statistics: [Sum]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_3XX_Count
    aws_dimensions: [TargetGroup, LoadBalancer]
    aws_statistics: [Sum]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_4XX_Count
    aws_dimensions: [TargetGroup, LoadBalancer]
    aws_statistics: [Sum]
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_5XX_Count
    aws_dimensions: [TargetGroup, LoadBalancer]
    aws_statistics: [Sum]
  - aws_namespace: "AWS/Billing"
    aws_dimensions: [Currency,ServiceName]
    aws_dimensions_select:
      Currency: [USD]
    aws_metric_name: EstimatedCharges
    aws_statistics: [Sum, Average]
    set_timestamp: false
```

We are looking for a solution other than simply reducing the number of metrics scraped. Can you provide a "scrape_delay" option that will wait a pre-defined time interval after completing a scrape and beginning the next scrape?
