### ISSUE TITLE
Multiple same HELP/TYPE lines for DynamoDB metrics

### ISSUE THREAD

**Issue by marceldegraaf** [prometheus/cloudwatch_exporter#18]
We're pulling DynamoDB metrics from CloudWatch, and we're interested in individual table metrics (e.g. `ConsumedReadCapacity` for a table `foo_production`), and the global secondary index metrics on a table (e.g. `ConsumedReadCapacity` for global secondary index `bar` on the `foobar_production` table).

Our configuration for `cloudwatch-exporter` looks like this:

```
- aws_namespace: "AWS/DynamoDB"
  aws_metric_name: "ProvisionedReadCapacityUnits"
  aws_dimensions:
    - TableName
  aws_dimension_select_regex:
    TableName:
      - "(.*)_production"

- aws_namespace: "AWS/DynamoDB"
  aws_metric_name: "ProvisionedReadCapacityUnits"
  aws_dimensions:
    - TableName
    - GlobalSecondaryIndexName
  aws_dimension_select_regex:
    TableName:
      - "(.*)_production"
```

However, this leads to two occurrences of the same `HELP` and `TYPE` lines for these metrics:

```
# HELP aws_dynamodb_provisioned_read_capacity_units_sum CloudWatch metric AWS/DynamoDB ProvisionedReadCapacityUnits Dimensions: [TableName] Statistic: Sum Unit: Count
# TYPE aws_dynamodb_provisioned_read_capacity_units_sum gauge
...
# HELP aws_dynamodb_provisioned_read_capacity_units_sum CloudWatch metric AWS/DynamoDB ProvisionedReadCapacityUnits Dimensions: [TableName, GlobalSecondaryIndexName] Statistic: Sum Unit: Count
# TYPE aws_dynamodb_provisioned_read_capacity_units_sum gauge
```

Prometheus doesn't like this: `text format parsing error in line 111: second HELP line for metric name "aws_dynamodb_provisioned_read_capacity_units_sum"`

I was hoping #11 would fix this, but of course even with a custom `HELP` text, the `TYPE` will still be duplicated, and thus be invalid.

Is there a way to get around this, and have both table and global secondary index data in Prometheus?
