### ISSUE TITLE
Detailed DEBUG info for CloudWatch exporter

### ISSUE THREAD

**Issue by tra0x** [prometheus/cloudwatch_exporter#181]
Hi there, 

We're trying to grab CloudWatch metrics like so

```
data:
  config.yml: |
    region: us-west-2
    period_seconds: 120
    metrics:
    - aws_namespace: CloudAMQP/Server metrics
      aws_metric_name: Cpu/user
      aws_dimensions: [InstanceName]
```

The metrics do exist in CloudWatch as you can see here (we've also made sure we're targeting the correct region)
![image](https://user-images.githubusercontent.com/13026244/55651590-1a192d00-57b7-11e9-810b-aca5e80077c5.png)

But for some reason the CloudWatch exporter does not grab them..

We're a little confused as to why it's not being grabbed. We're not seeing any value for `cloudwatch_exporter_scrape_error` or any errors in the pod logs. 

Is there a way to add debug info for the CloudWatch exporter so that it logs some more information and doesn't silently fail. 

Thanks!
