### ISSUE TITLE
DynamoDB metrics exported but not scraped

### ISSUE THREAD

**Issue by alexsstock** [prometheus/cloudwatch_exporter#194]
Hello, nice people.

I've read a few of the issues here on DynamoDB and I'm having trouble getting prom to scrape what I am exporting with the cw exporter.

My output looks like this:

```
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total 2456.0
# HELP aws_dynamodb_consumed_read_capacity_units_average CloudWatch metric AWS/DynamoDB ConsumedReadCapacityUnits Dimensions: [TableName] Statistic: Average Unit: Count
# TYPE aws_dynamodb_consumed_read_capacity_units_average gauge
aws_dynamodb_consumed_read_capacity_units_average{job="aws_dynamodb",instance="",table_name="mytable",} 1.118673647469459 1562952900000
# HELP aws_kinesis_get_records_latency_average CloudWatch metric AWS/Kinesis GetRecords.Latency Dimensions: [StreamName] Statistic: Average Unit: Milliseconds
# TYPE aws_kinesis_get_records_latency_average gauge
aws_kinesis_get_records_latency_average{job="aws_kinesis",instance="",stream_name="mystream",} 12.397826086956522 1562952900000
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 0.027452328
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
```

I can scrape the built in metrics with a single value, like cloudwatch_requests_total

my dynamo metrics that have 2 values are not getting scraped.

i don't understand why i have 2 values, here is my config:

```
---
region: us-east-1
metrics:
 - aws_namespace: AWS/DynamoDB
   aws_metric_name: ConsumedReadCapacityUnits
   aws_dimensions: [TableName]
   aws_dimension_select_regex:
     TableName: ["mytable"]
   aws_statistics: [Average]
   period_seconds: 60
```

I'm sure I am missing something obvious, any assistance is greatly appreciated.
