### ISSUE TITLE
Lambda errors aws_statistics

### ISSUE THREAD

**Issue by nenych** [prometheus/cloudwatch_exporter#200]
Hello.
How can I use the aws_statistics parameter for the lambda error?
My configuration:
```
---
region: <region>
metrics:
 - aws_namespace: AWS/Lambda
   aws_metric_name: Errors
   aws_dimensions: [FunctionName]
```
The datapoints i get:
```
aws_lambda_errors_sample_count{job="aws_lambda",instance="",function_name="<lambda_name>",} 36.0 1565798460000
```
Here is datapoints from the Grafana:
```
40:Array[28,1565797920000]
41:Array[21,1565797980000]
42:Array[14,1565798040000]
43:Array[12,1565798100000]
44:Array[5,1565798160000]
45:Array[5,1565798220000]
46:Array[6,1565798280000]
47:Array[2,1565798340000]
48:Array[13,1565798400000]
49:Array[3,1565798460000]
50:Array[4,1565798520000]
51:Array[5,1565798580000]
52:Array[7,1565798640000]
53:Array[12,1565798700000]
54:Array[12,1565798760000]
55:Array[4,1565798820000]
56:Array[5,1565798880000]
57:Array[2,1565798940000]
58:Array[2,1565799000000]
59:Array[5,1565799060000]
```

Can you explain what does value 36 mean? 
And yes both values (grafana and exporter) uses SampleCount statistic, and for the same lambda function.
