### ISSUE TITLE
Exporter not picking up AWS/Kafka metrics 

### ISSUE THREAD

**Issue by jim5252** [prometheus/cloudwatch_exporter#237]
I am able to get metrics using the exporter tool for other AWS resources but when attempting to use for Kafka, no metrics are being retrieved:

`HELP tagging_api_requests_total API requests made to the Resource Groups Tagging API
 TYPE tagging_api_requests_total counter

 HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.

 TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 0.0403737

 HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.

 TYPE cloudwatch_exporter_scrape_error gauge

cloudwatch_exporter_scrape_error 0.0

 HELP cloudwatch_requests_total API requests made to CloudWatch

 TYPE cloudwatch_requests_total counter

cloudwatch_requests_total{action="listMetrics",namespace="AWS/Kafka",} 16.0`

There is not any examples of using Kafka in the repository, does anyone know if it has been successfully used for Kafka before?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by jim5252** [comment]
Thank you, i shall direct my question there.

**Comment by RmMsr** [comment]
Hi @jim5252 ,

we experienced the same problem. After quite a while of experimenting we noticed that the naming is crucial. For example the dimensions must be identical to the AWS naming with case and whitespace.

Example:

```
metrics:
  - aws_namespace: AWS/Kafka
    aws_metric_name: KafkaDataLogsDiskUsed
    aws_dimensions: [Broker ID, Cluster Name]
    aws_statistics: [Maximum]
```

**Comment by vasrem** [comment]
BTW guys, JFYI you have to specify **both** aws_dimensions to get the metrics back as @RmMsr described.

**Comment by pmccau** [comment]
Note that to get any tag filters to work you need to pass in a comma-separated **string** value in lieu of a list (for some reason?), for example:

```yaml
       aws_dimensions: [Broker ID, Cluster Name]
       ...
       aws_tag_select:
          tag_selections:
            owner: ["your_owner_here"]
          resource_type_selection: "kafka:cluster"
          resource_id_dimension: Broker ID, Cluster Name, Topic   # Can omit Topic for less granular output
```
