### ISSUE TITLE
Help - How to convert this Grafana Query to exporter config

### ISSUE THREAD

**Issue by bzon** [prometheus/cloudwatch_exporter#244]
I can't seem to find the right config to convert this Grafana Cloudwatch Datasource query.

![Screenshot 2020-01-02 at 11 26 26](https://user-images.githubusercontent.com/19391568/71662726-c9892d00-2d52-11ea-8160-cd28b89d3333.png)

My current config is:

```
      region: us-east-1
      metrics:
      - aws_namespace: AWS/Route53
        aws_metric_name: HealthCheckStatus
        aws_statistics: [Minimum]
        aws_dimension_select_regex:
          HealthCheckId: [".*"]
```
