### ISSUE TITLE
to get region name in the metrics when it is scrapped by prometheus

### ISSUE THREAD

**Issue by chitender** [prometheus/cloudwatch_exporter#249]
Hello,

we are using the cloudwatch exporter to monitor the lambda throttles count across multiple region. below is our configuration:
```
---
region: us-east-1
metrics:
 - role_arn: arn:aws:iam::190020191201:role/prometheus-read-only
   aws_namespace: AWS/Lambda
   aws_metric_name: Throttles
   aws_dimensions: [FunctionName]
   aws_statistics: [Sum]
   range_seconds: 300
   set_timestamp: false
region: ap-south-1
metrics:
 - role_arn: arn:aws:iam::190020191201:role/prometheus-read-only
   aws_namespace: AWS/Lambda
   aws_metric_name: Throttles
   aws_dimensions: [FunctionName]
   aws_statistics: [Sum]
   range_seconds: 300
   set_timestamp: false
region: ap-southeast-1
metrics:
 - role_arn: arn:aws:iam::190020191201:role/prometheus-read-only
   aws_namespace: AWS/Lambda
   aws_metric_name: Throttles
   aws_dimensions: [FunctionName]
   aws_statistics: [Sum]
   range_seconds: 300
   set_timestamp: false
```
as we are monitoring services which are in multiple region, we are looking if we can get the region Id or region name in the metrics also in addition to aws cloudwatch metrics.
