### ISSUE TITLE
Resource type for SQS

### ISSUE THREAD

**Issue by fblanke** [prometheus/cloudwatch_exporter#251]
Hi! 

I am trying to setup a scrape of message size of dlq to alert us when we get any content in them.

I might be both stupid and blind, but I can for my life not find the correct `resource_type_selection` when scraping an SQS. The docs says that: "Required, under aws_tag_select. Specify the [resource type](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#genref-aws-service-namesspaces) to filter on." And the [docs for SQS](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonsqs.html#amazonsqs-queue) says that the resource type simply is "queue"

But still the following will not work:
`- aws_namespace: AWS/SQS
    aws_metric_name: ApproximateNumberOfMessagesVisible
    aws_dimensions: [QueueName]
    aws_tag_select:
      tag_selections:
        Type: ["dlq"]
        Environment: ["systest"]
      resource_type_selection: "queue"
      resource_id_dimension: QueueName
    aws_statistics: [Sum]`

It gives:
`WARNING: CloudWatch scrape failed
com.amazonaws.services.resourcegroupstaggingapi.model.InvalidParameterException: Unsupported service=queue in ResourceTypeFilter - queue: (Service: AWSResourceGroupsTaggingAPI; Status Code: 400; Error Code: InvalidParameterException;`

I've also tried with `sqs:queue`, `*` and `queue*`.

Any help or pointers?

**Comment by fblanke** [comment]
Resolved now. Even though it was very unclear from AWS, you use ONLY the service when there are no specific resource types. Such as:
`- aws_namespace: AWS/SQS
    aws_metric_name: ApproximateNumberOfMessagesVisible
    aws_dimensions: [QueueName]
    aws_tag_select:
      tag_selections:
        Type: ["dlq"]
        Environment: ["systest"]
      resource_type_selection: sqs
      resource_id_dimension: QueueName
    aws_statistics: [Sum]`

**Comment by konstantin-kornienko** [comment]
Another working example to collect metrics from all queues having the specific tag (with any value in it):

```yaml
- aws_namespace: AWS/SQS
  aws_metric_name: ApproximateNumberOfMessagesVisible
  aws_dimensions:
    - QueueName
  aws_statistics:
    - Average
  aws_tag_select:
    resource_type_selection: "sqs"
    resource_id_dimension: QueueName
    tag_selections:
      Environment:
```
