### ISSUE TITLE
aws_resource_info label bug

### ISSUE THREAD

**Issue by aperigault** [prometheus/cloudwatch_exporter#260]
Hi,

My example config :

 ```
- aws_namespace: AWS/VPN
      aws_metric_name: TunnelState
      aws_dimensions: [TunnelIpAddress]
      aws_statistics: [Minimum]
      aws_tag_select:
        resource_type_selection: ec2:vpn-connection
        resource_id_dimension: TunnelIpAddress
```

Result:

> aws_resource_info{job="aws_vpn",instance="",arn="arn:aws:ec2:us-west-2:xxxxxxxxxxxx:vpn-connection/vpn-000394847484ab",**tunnel_ip_address="vpn-000394847484ab"**,tag_Name="test"}
> aws_vpn_tunnel_data_in_sum{job="aws_vpn",instance="",tunnel_ip_address="52.49.10.12"}

Expected result:

> 
> aws_resource_info{job="aws_vpn",instance="",arn="arn:aws:ec2:us-west-2:xxxxxxxxxxxx:vpn-connection/vpn-000394847484ab",**tunnel_ip_address="52.49.10.12"**,tag_Name="test"}
> aws_vpn_tunnel_data_in_sum{job="aws_vpn",instance="",tunnel_ip_address="52.49.10.12"}

Because of this bug I can't link my **aws_vpn_tunnel_data_in_sum** with **aws_resource_info**.

The bug seems to be related to this line but i don't know how to fix it:
https://github.com/prometheus/cloudwatch_exporter/blob/4e3c1537fb1dbc9b7c2fe380b670a5c084631d92/src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java#L649

Thanks

**Comment by brian-brazil** [comment]
The code is working as expected here, I think your issue here is that TunnelIpAddress is not an ARN.

**Comment by aperigault** [comment]
TunnelIpAddress is not suppose to be an ARN.
Have you a workaround for my usecase ? I do not want to collect my VPN metrics by `VpnId` dimension, it is too restrictive. Each VPN connection have two IP adress and I need to keep this granularity.

**Comment by brian-brazil** [comment]
If TunnelIpAddress is not an ARN, then it is incorrect to provide it as resource_id_dimension.

**Comment by aperigault** [comment]
Ok, so this is a limitation in this exporter and there is no plan to add this feature ?

**Comment by brian-brazil** [comment]
This appears to be a misconfiguration on your part.

**Comment by aperigault** [comment]
I try with this configuration:
```
- aws_namespace: AWS/VPN
     aws_metric_name: TunnelState
     aws_dimensions: [TunnelIpAddress]
     aws_statistics: [Minimum]
     aws_tag_select:
       resource_type_selection: ec2:vpn-connection
       resource_id_dimension: VpnId
```

Now I have two metrics without any link between it :
> aws_resource_info{job="aws_vpn",instance="",arn="arn:aws:ec2:us-west-2:xxxxxxxxxxxx:vpn-connection/vpn-000394847484ab",vpn_id="vpn-000394847484ab",tag_Name="test"}

> aws_vpn_tunnel_data_in_sum{job="aws_vpn",instance="",tunnel_ip_address="52.49.10.12"}

I'm open to any suggestions.
