### ISSUE TITLE
Feature request: include tags in cloudfront labels

### ISSUE THREAD

**Issue by hryamzik** [prometheus/cloudwatch_exporter#285]
Cloudfront metrics have only ID label to identify the distribution and that's not human readable. Ability to use tags would help a lot.

**Comment by hryamzik** [comment]
Oops, `aws_tag_select` worked but that was not intuitive:

```yaml
    aws_tag_select:
      resource_type_selection: cloudfront
      resource_id_dimension: Requests
```
