### ISSUE TITLE
Pulling CWAgent Metrics

### ISSUE THREAD

**Issue by nomeelnoj** [prometheus/cloudwatch_exporter#292]
Hello,

We use the cloudwatch agent to gather some metrics from some of our more custom hosts, and I am trying to scrape these into prometheus using the cloudwatch exporter.  

I have confirmed the metric name and namespace using `aws cloudwatch list-metrics --namespace CWAgent` and the metric names returned all match the config I am using.  However, I am unable to get these metrics and cloudwatch exporter is not showing any scrape failures or errors in the logs.

Here is a snippet of our config:

```
      region: us-east-1
      metrics:
      - aws_namespace: CWAgent
        aws_metric_name: cpu_usage_iowait
        aws_dimensions: ["Service"]
        aws_dimension_select:
          "Service": [my-service]

      - aws_namespace: CWAgent
        aws_metric_name: cpu_usage_user
        aws_dimensions: ["Service"]
        aws_dimension_select:
          "Service": [my-service]

      - aws_namespace: CWAgent
        aws_metric_name: cpu_usage_system
        aws_dimensions: ["Service"]
        aws_dimension_select:
          "Service": [my-service]
```

Any idea what could be going on here?
