### ISSUE TITLE
CWE is not showing metrics for DynamoDB ThrottlingEvents

### ISSUE THREAD

**Issue by sanagarw** [prometheus/cloudwatch_exporter#293]
Created config as 

```
region: us-east-1
metrics:
  - aws_namespace: AWS/DynamoDB
    aws_metric_name: ThrottledRequests
    aws_dimensions:
    - TableName
    - Operation
  - aws_namespace: AWS/DynamoDB
    aws_metric_name: ReadThrottleEvents
    aws_dimensions:
    - TableName
    - GlobalSecondaryIndexName
  - aws_namespace: AWS/DynamoDB
    aws_metric_name: WriteThrottleEvents
    aws_dimensions:
    - TableName
    - GlobalSecondaryIndexName
```

But couldn't see the Metrics in cloudwatch exporter for above metrics?

I could see metrics in cloudwatch for WriteThrottleEvents

```
$ aws cloudwatch list-metrics --namespace AWS/DynamoDB --metric WriteThrottleEvents --region us-east-1
{
    "Metrics": [
        {
            "Namespace": "AWS/DynamoDB",
            "MetricName": "WriteThrottleEvents",
            "Dimensions": [
                {
                    "Name": "TableName",
                    "Value": "xxx-xxx-xxx"
                }
            ]
        }
    ]
}

```
