### ISSUE TITLE
aws_resource_info while using aws_tag_select causes prometheus/expfmt parsing errors due to multiple same HELP/TYPE lines

### ISSUE THREAD

**Issue by mikhailadvani** [prometheus/cloudwatch_exporter#297]
I tried running the prometheus cloudwatch exporter with 2 configurations separately for EC2 CPU info

Scenario 1:
```
region: us-east-1
metrics:
- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_tag_select:
    tag_selections:
      aws_service: ["opsworks"]
    resource_type_selection: "ec2:instance"
    resource_id_dimension: InstanceId
  aws_statistics: [Maximum]
```

Scenario 2:
```
region: us-east-1
metrics:
- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_dimension_select:
    InstanceId: [i-X, i-Y, i-Z]
  aws_statistics: [Maximum]
```

The parsing of output in scenario 2 is fine but parsing the output of scenario 1 fails with error: `Invalid decode: text format parsing error in line 12: second HELP line for metric name "aws_resource_info".`

The instances filtered by the aws_tag_select in scenario 1 are identical to the ones specified inline in scenario 2.

**Comment by brian-brazil** [comment]
Is that the whole configuration?

**Comment by mikhailadvani** [comment]
yes. that is the whole configuration in each of the scenarios.

**Comment by brian-brazil** [comment]
Okay I see the problem, the MetricFamilySamples for aws_resource_info is being created once per mapping rather than once per scrape. That's easy to fix, would you like to have a go at it?

**Comment by mikhailadvani** [comment]
Have raised a PR for the issue which tackle my scenario(single metric with aws_tag_select) but doesn't tackle something like example below(multiple metrics with aws_tag_select)
```
region: us-east-1
metrics:
- aws_namespace: AWS/RDS
  aws_metric_name: CPUUtilization
  aws_dimensions: [DBInstanceIdentifier]
  aws_tag_select:
    tag_selections:
      Env: ["QA"]
    resource_type_selection: "rds:db"
    resource_id_dimension: DBInstanceIdentifier
  aws_statistics: [Maximum]
- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_tag_select:
    tag_selections:
      aws_service: ["opsworks"]
    resource_type_selection: "ec2:instance"
    resource_id_dimension: InstanceId
  aws_statistics: [Maximum]
```
The only way I could think of tackling this was to relabel aws_resource_info but that would break existing integrations and hence did not go ahead with that approach.

P.S. Did not add tests since I wasn't sure how "HELP" tests are to be written.
