### ISSUE TITLE
PrometheusDuplicateTimestamps CloudFront Scrapping

### ISSUE THREAD

**Issue by jlsan92** [prometheus/cloudwatch_exporter#311]
Version `prom/cloudwatch-exporter:cloudwatch_exporter-0.8.0`

Hi, thanks for the development of this exporter 🙏

I believe I found a bug. I'm receiving the following "warning" alert `PrometheusDuplicateTimestamps` after enabling the following service scraper

```yaml
      - aws_namespace: AWS/CloudFront
        aws_metric_name: TotalErrorRate
        aws_statistics: [Average]
        aws_dimensions: [DistributionId, Region]
        aws_dimension_select:
         Region: [Global]
```

As described on the examples => https://github.com/prometheus/cloudwatch_exporter/blob/master/example.yml#L196

Debug log output coming from Prometheus

```
level=debug ts=2020-11-27T13:59:46.958Z caller=scrape.go:1250 component="scrape manager" scrape_pool=monitoring/prometheus-cloudwatch-exporter/0 target=http://100.90.1.2:9106/metrics msg="Duplicate sample for timestamp" series="aws_cloudfront_total_error_rate_average{job=\"aws_cloudfront\",instance=\"\",region=\"Global\",distribution_id=\"XXXXXXX\",}"
```

How this alert gets triggered => https://github.com/prometheus/prometheus/blob/34c7f6e3c4db66b6f630b2ba55f84b13f50cbb21/documentation/prometheus-mixin/alerts.libsonnet#L142

Thanks!
