### ISSUE TITLE
Memory leak in 0.10.0

### ISSUE THREAD

**Issue by der-eismann** [prometheus/cloudwatch_exporter#334]
Hey everyone, we are experiencing a memory leak with the latest release. After starting the memory is continually increasing until the pod gets an OOM error because it's hitting the limit. 

![workloads-argocd](https://user-images.githubusercontent.com/10406217/116694669-d7d76f80-a9bf-11eb-8def-5dffb0b11daf.png)

We only export 42 metrics, so it isn't that much. Is there an easy way to get a heap dump or something that helps?

This is our start command:
```
java -Xms300M -Xmx300M -jar /cloudwatch_exporter.jar 9106 /config/config.yaml
```

This is our config:
```yaml
---
region: eu-west-1

## ELB

metrics:
- aws_namespace: AWS/ELB
  aws_metric_name: HealthyHostCount
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Maximum]

- aws_namespace: AWS/ELB
  aws_metric_name: HTTPCode_Backend_2XX
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Sum]

- aws_namespace: AWS/ELB
  aws_metric_name: HTTPCode_Backend_5XX
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Sum]

- aws_namespace: AWS/ELB
  aws_metric_name: HTTPCode_ELB_5XX
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Sum]

- aws_namespace: AWS/ELB
  aws_metric_name: Latency
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Average, Maximum]

- aws_namespace: AWS/ELB
  aws_metric_name: RequestCount
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Sum]

## EBS Volumes

- aws_namespace: AWS/EBS
  aws_metric_name: VolumeReadOps
  aws_dimensions: [VolumeId]
  aws_statistics: [Average]
  aws_tag_select:
    tag_selections:
      kubernetes.io/created-for/pvc/namespace: ["default"]
    resource_type_selection: "ec2:volume"
    resource_id_dimension: VolumeId

- aws_namespace: AWS/EBS
  aws_metric_name: VolumeWriteOps
  aws_dimensions: [VolumeId]
  aws_statistics: [Average]
  aws_tag_select:
    tag_selections:
      kubernetes.io/created-for/pvc/namespace: ["default"]
    resource_type_selection: "ec2:volume"
    resource_id_dimension: VolumeId

- aws_namespace: AWS/EBS
  aws_metric_name: VolumeReadBytes
  aws_dimensions: [VolumeId]
  aws_statistics: [Average]
  aws_tag_select:
    tag_selections:
      kubernetes.io/created-for/pvc/namespace: ["default"]
    resource_type_selection: "ec2:volume"
    resource_id_dimension: VolumeId

- aws_namespace: AWS/EBS
  aws_metric_name: VolumeWriteBytes
  aws_dimensions: [VolumeId]
  aws_statistics: [Average]
  aws_tag_select:
    tag_selections:
      kubernetes.io/created-for/pvc/namespace: ["default"]
    resource_type_selection: "ec2:volume"
    resource_id_dimension: VolumeId

- aws_namespace: AWS/EBS
  aws_metric_name: VolumeQueueLength
  aws_dimensions: [VolumeId]
  aws_statistics: [Average]
  aws_tag_select:
    tag_selections:
      kubernetes.io/created-for/pvc/namespace: ["default"]
    resource_type_selection: "ec2:volume"
    resource_id_dimension: VolumeId

## RDS

- aws_namespace: AWS/RDS
  aws_metric_name: CPUUtilization
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: WriteIOPS
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: ReadIOPS
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: ReadLatency
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: NetworkReceiveThroughput
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: DatabaseConnections
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: ReplicaLag
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: DiskQueueDepth
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: FreeStorageSpace
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: OldestReplicationSlotLag
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: ReplicationSlotDiskUsage
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: FreeLocalStorage
  aws_dimensions: [DBClusterIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: ReadIOPS
  aws_dimensions: [DBClusterIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: WriteIOPS
  aws_dimensions: [DBClusterIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: CPUUtilization
  aws_dimensions: [DBClusterIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: DatabaseConnections
  aws_dimensions: [DBClusterIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: NetworkThroughput
  aws_dimensions: [DBClusterIdentifier]
  aws_statistics: [Average]

## ALB

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HealthyHostCount
  aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
  aws_statistics: [Maximum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: UnHealthyHostCount
  aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
  aws_statistics: [Minimum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_2XX_Count
  aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_3XX_Count
  aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_4XX_Count
  aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_5XX_Count
  aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_ELB_5XX_Count
  aws_dimensions: [AvailabilityZone, LoadBalancer]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: RequestCount
  aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: TargetResponseTime
  aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
  aws_extended_statistics: [p50, p90, p95, p99]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: ActiveConnectionCount
  aws_dimensions: [LoadBalancer]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: ConsumedLCUs
  aws_dimensions: [LoadBalancer]
  aws_statistics: [Sum]

```
