### ISSUE TITLE
Connection to server fails when using `aws_tag_select`

### ISSUE THREAD

**Issue by pedro-brentan** [prometheus/cloudwatch_exporter#335]
Trying to use the follow metric selection's configuration drives me to a lot of errors when scrapping cloudwatch. Using dimension selection works "fine" (not so fine, it gets metrics 10 minutes delayed). 

```
    metrics:
    - aws_namespace: AWS/ApplicationELB
      aws_metric_name: RequestCount
      aws_dimensions: [LoadBalancer]
      aws_tag_select:
        tag_selections:
          prometheus_scrapping: ["true"]
        resource_type_selection: "elasticloadbalancing:loadbalancer"
        resource_id_dimension: LoadBalancer
      aws_statistics: [Sum]
```

It gives me errors like:

```
WARNING: CloudWatch scrape failed
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: The target server failed to respond
```
```
WARNING: CloudWatch scrape failed
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Received close_notify during handshake
```
```
WARNING: CloudWatch scrape failed
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Connect to monitoring.us-east-1.amazonaws.com:443 [monitoring.us-east-1.amazonaws.com/10.0.253.163] failed: Read timed out
```
```
WARNING: CloudWatch scrape failed
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: readHandshakeRecord
```
