### ISSUE TITLE
"AWS/Billing" metrics do not appear

### ISSUE THREAD

**Issue by FPurchess** [prometheus/cloudwatch_exporter#35]
Hi,

first of all thanks for your work! While testing the exporter, it turned out, that I was not able to fetch estimated charges (using a valid iam role). cloudwatch_exporter does not show any error in logs or scrape_error counter.

Here is a sample config:
```
---
region: us-east-1
metrics:
 - aws_namespace: AWS/Billing
   aws_metric_name: EstimatedCharges
   aws_dimensions: [ServiceName, LinkedAccount, Currency]
   aws_dimension_select:
     Currency: [USD]
   aws_statistics: [Sum]
```

**Comment by FPurchess** [comment]
I just realized the period was just too short. However, a log showing the datapoints received by the API would have come in very handy here ;)

**Comment by estahn** [comment]
@FPurchess What have you done to fix this?

**Comment by estahn** [comment]
If anyone else comes across this. Add `range_seconds: 86400`.
```
  region: us-east-1
  period_seconds: 60
  metrics:
    - aws_namespace: AWS/Billing
      aws_metric_name: EstimatedCharges
      aws_dimensions: [ServiceName, LinkedAccount, Currency]
      aws_dimension_select:
        Currency: [USD]
      aws_statistics: [Sum]
      range_seconds: 86400
```
