### ISSUE TITLE
Add AWS Account ID to labels

### ISSUE THREAD

**Issue by sean-nixon** [prometheus/cloudwatch_exporter#357]
We have a multi-account environment and would like to use the `role_arn` configuration to export metrics across our accounts from one instance of the cloudwatch_exporter. However, there seems to be no way to differentiate between metrics from the different accounts. Because of this, role_arn doesn't really help us and we'd be forced to run one instance of the exporter for each account, pull from each of them, and do some intricate relabeling in the prometheus configuration based on the metalabels from the scrape targets.

It would be highly useful if the source AWS account ID was added as a label (perhaps `account_id`) to each of the exported metrics. This could be determined from a GetCallerIdentity to STS. If a role_arn is provided, it could also be parsed from that value.

Barring this functionality, an ability to specify custom labels in each metric would also suffice.

Would the above functionality be considered in this project? If so, I would be willing to give a go at a PR.

**Comment by matthiasr** [comment]
Can you give an example how you would configure the exporter to pull metrics from multiple accounts with one configuration?

**Comment by matthiasr** [comment]
I am leaning towards

> Barring this functionality, an ability to specify custom labels in each metric would also suffice.

since this would be more general. Someone else may not want to use account IDs but some other identifier, but they'd know what they want when writing the configuration.

**Comment by sean-nixon** [comment]
@matthiasr On second look at the documentation, it looks like I was probably mistaken and it's not possible to pull metrics from multiple accounts with one configuration since `role_arn` is a global configuration. I was initially thinking a configuration like this, but I believe it's invalid now.

```
region: us-west-2
metrics:
 - aws_namespace: AWS/ELB
   aws_metric_name: RequestCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [myLB]
   aws_statistics: [Sum]
   role_arn: <account1>
 - aws_namespace: AWS/ELB
   aws_metric_name: RequestCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [myLB]
   aws_statistics: [Sum]
   role_arn: <account2>
```

I think the request still has value since it removes the need to do relabeling in the prometheus scraper configuration. I understand your logic for favoring custom labels over only the account ID and that would be great to have.
