### ISSUE TITLE
Previous scraped metric data is presisited for 5 mins when cloudwatch responds no data

### ISSUE THREAD

**Issue by venkat330** [prometheus/cloudwatch_exporter#359]
Hello,

I am just trying to recon the AWS cloud watch source data & prom scraped data for ApiGatway and notice the strange behaviour of Prometheus persisting previous scarped metric value when no metric data was reported by cloud watch for a max period of 5 mins. attached image for your reference

Promo - API -Gateway (data scraped by Cloudwatch-exporter)
CW - API -Gateway (data reported by Cloudwatch direct)

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/3581630/132483178-ed769354-5925-4240-a7fd-21961ecedafc.png)

Scenario 1: First data was reported @18:43 by CW & till 19:08 cloudwatch reported no response.

For this Prometheus scraped data, shows the value as 1 from 18:43 to 18:48 & then it started reporting empty values.

Scenario 2: Count data was reported @19:09  & 19:13 by CW & till 19:09 cloudwatch reported no response.

for this case, Prometheus started reporting data from 19:09 till 19:18 as. 1 then started reporting null.

configuration used:

```
  config.yml: |-
    region: ap-test-2
    range_seconds: 60
    delay_seconds: 60
    period_seconds: 60
    metrics:
    - aws_namespace: AWS/ApiGateway
      aws_metric_name: Count
      aws_dimensions: [ApiName, Method, Resource, Stage]
      aws_dimension_select:
        Resource: [/test/v1/ap]
      aws_statistics: [Sum]

```

Because of this behaviour, we are not able to report correct count data, Please advise us on how to go forward.

Thanks
Venkat.S
