### ISSUE TITLE
CWAgent metrics error

### ISSUE THREAD

**Issue by pikodd** [prometheus/cloudwatch_exporter#361]
Exporter can't see CloudWatch Agent metrics, EC2 metrics are ok.
Exporter config
```
region: us-west-1
metrics:
 - aws_namespace: CWAgent
   aws_metric_name: disk_used_percent
   aws_dimensions: [InstanceId, path]

 - aws_namespace: CWAgent
   aws_metric_name: mem_used_percent
   aws_dimensions: [InstanceId]

 - aws_namespace: AWS/EC2
   aws_metric_name: CPUUtilization
   aws_dimensions: [InstanceId]
   aws_statistics: [Average]

 - aws_namespace: AWS/EC2
   aws_metric_name: DiskReadOps
   aws_dimensions: [InstanceId]
   aws_statistics: [Sum]

 - aws_namespace: AWS/EC2
   aws_metric_name: DiskWriteOps
   aws_dimensions: [InstanceId]
   aws_statistics: [Sum]
```

cloudwatch_exporter:9106/metrics output:

```
# HELP aws_ec2_cpuutilization_average CloudWatch metric AWS/EC2 CPUUtilization Dimensions: [InstanceId] Statistic: Average Unit: Percent
# TYPE aws_ec2_cpuutilization_average gauge
aws_ec2_cpuutilization_average{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 3.4451977401139557 1631820720000
aws_ec2_cpuutilization_average{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 3.899759192369724 1631820660000
aws_ec2_cpuutilization_average{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 3.29828528358573 1631820660000
aws_ec2_cpuutilization_average{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.5811475409836033 1631820600000
aws_ec2_cpuutilization_average{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxxf",} 3.2557377049165757 1631820720000
aws_ec2_cpuutilization_average{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 1.627489117347288 1631820780000
# HELP aws_ec2_disk_read_ops_sum CloudWatch metric AWS/EC2 DiskReadOps Dimensions: [InstanceId] Statistic: Sum Unit: Count
# TYPE aws_ec2_disk_read_ops_sum gauge
aws_ec2_disk_read_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820660000
aws_ec2_disk_read_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820600000
aws_ec2_disk_read_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820720000
aws_ec2_disk_read_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820660000
aws_ec2_disk_read_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820720000
aws_ec2_disk_read_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820780000
# HELP aws_ec2_disk_write_ops_sum CloudWatch metric AWS/EC2 DiskWriteOps Dimensions: [InstanceId] Statistic: Sum Unit: Count
# TYPE aws_ec2_disk_write_ops_sum gauge
aws_ec2_disk_write_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820720000
aws_ec2_disk_write_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820660000
aws_ec2_disk_write_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820660000
aws_ec2_disk_write_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820600000
aws_ec2_disk_write_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxxf",} 0.0 1631820720000
aws_ec2_disk_write_ops_sum{job="aws_ec2",instance="",instance_id="i-xxxxxxxxxxx",} 0.0 1631820780000
# HELP aws_resource_info AWS information available for resource
# TYPE aws_resource_info gauge
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 0.293217931
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
# HELP tagging_api_requests_total API requests made to the Resource Groups Tagging API
# TYPE tagging_api_requests_total counter
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total{action="getMetricStatistics",namespace="AWS/EC2",} 180.0
cloudwatch_requests_total{action="listMetrics",namespace="AWS/EC2",} 30.0
cloudwatch_requests_total{action="listMetrics",namespace="CWAgent",} 20.0
# HELP cloudwatch_requests_created API requests made to CloudWatch
# TYPE cloudwatch_requests_created gauge
cloudwatch_requests_created{action="getMetricStatistics",namespace="AWS/EC2",} 1.631821451977E9
cloudwatch_requests_created{action="listMetrics",namespace="AWS/EC2",} 1.631821451893E9
cloudwatch_requests_created{action="listMetrics",namespace="CWAgent",} 1.631821451859E9
```
