### ISSUE TITLE
Unable to use aws_tag_select for Autoscaling group

### ISSUE THREAD

**Issue by ashishvaishno** [prometheus/cloudwatch_exporter#367]
Hello,

I am trying to use aws_tag_select to select few asg's
I have tried the below config 
```
      - aws_namespace: AWS/AutoScaling
        aws_metric_name: GroupDesiredCapacity
        aws_dimensions: [ AutoScalingGroupName ]
        aws_statistics: [ Maximum ]
        aws_tag_select:
          tag_selections:
            Name: ["xxxxxxx"]
          resource_type_selection: "autoscaling:autoScalingGroup"
          resource_id_dimension: AutoScalingGroupName
```

I have replaced resource_type_selection with the below values and none of them worked for me 
```
autoScaling:autoScalingGroup
autoScaling:autoScalingGroupName
autoScalingGroup:autoScalingGroupName
autoscaling:autoScalingGroup
autoscaling:autoScalingGroupName
```
Can you provide me some info , how to fetch the information?

Regards
Ashish

**Comment by matthiasr** [comment]
Unfortunately I am as lost as you are on this. From the `service:resourceType` format, [based on](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#genref-aws-service-namesspaces) the [ARN format for autoscaling](https://docs.aws.amazon.com/autoscaling/ec2/userguide/control-access-using-iam.html), I would expect `autoscaling:autoScalingGroup` to work, but apparently it does not.

[This StackOverflow answer](https://serverfault.com/a/936571) suggests that the resource groups tagging API does not support autoscaling, but [this page](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/supported-services.html) lists it.

Maybe the problem is with something else? In the [examples](https://github.com/prometheus/cloudwatch_exporter/blob/8808a746634289754505c0546937a309fd557385/examples/AutoScaling.yml#L39-L44), the statistic is `Average` and not all metrics support all statistics.

**Comment by JesusFrontelo** [comment]
@ashishvaishno Have you tried putting everything lowercase in the resource type section? 
something like: 
autoscaling:autoscalinggroupname

**Comment by matthiasr** [comment]
Awesome, thank you!

**Comment by lukasmrtvy** [comment]
no results with 
```
region: us-east-1
metrics:
- aws_dimensions:
  - AutoScalingGroupName
  aws_metric_name: GroupDesiredCapacity
  aws_namespace: AWS/AutoScaling
  aws_statistics:
  - Average
  aws_tag_select:
    tag_selections:
      Name: ["myasgname"]
    resource_type_selection: "autoscaling"
    resource_id_dimension: AutoScalingGroupName
```
ideas? Thanks
