### ISSUE TITLE
[k8s] mounting into "/" is prohibited and cannot find "java"

### ISSUE THREAD

**Issue by zanhsieh** [prometheus/cloudwatch_exporter#37]
Hi,

I tried to put cloudwatch_exporter with k8s at AWS. I hit this error:

```
$ kubectl logs cloudwatch-556263178-eqd6t 
Timestamp: 2016-08-17 01:03:19.851546984 +0000 UTC
Code: System error

Message: mounting into / is prohibited
```

I share my configmap, deployment, and service as:

```
$ cat ./cloudwatch-configmap.yaml | nc termbin.com 9999
http://termbin.com/v80k
$ cat ./cloudwatch-deployment.yaml.share | nc termbin.com 9999
http://termbin.com/ndop
$ cat ./cloudwatch-service.yaml | nc termbin.com 9999
http://termbin.com/6rym
```

Also, after modifying / recompiling prom/cloudwatch-exporter Dockerfile and re-deploy into AWS/k8s, it keeps complaining cannot find "java". I suspect the default Dockerfile was written couple days back during openjdk still on 1.7. Now it's 1.8 but alternatives does not get proper set up. This is my fix:

```
$ cat Dockerfile | nc termbin.com 9999
http://termbin.com/856g
````

BTW, the base image for my k8s is debian jessie.

**Comment by brian-brazil** [comment]
This looks to be a kubernetes problem, and nothing to do with the cloudwatch exporter. I'd check the `volumeMounts` line.

**Comment by sstarcher** [comment]
@zanhsieh Kubernetes as you saw does not allow you to mount volumes to `/`.  Kubernetes does not support mounting a file it always mounts a folder.  You should not have to rebuild the docker image.  You should be able to just modify the entry point as I did below.

```yaml
    spec:
      containers:
      - image: prom/cloudwatch-exporter:latest
        name: prometheus-cloudwatch-exporter
        command: ["java", "-jar", "/cloudwatch_exporter.jar", "9106", "/etc/prometheus/config.yml" ]
        ports:
        - containerPort: 9100
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-cloudwatch-exporter
```
