### ISSUE TITLE
S3 metrics not being pulled

### ISSUE THREAD

**Issue by garryknox** [prometheus/cloudwatch_exporter#38]
I've been using the docker container for a while and I thought everything was working correctly.  I just noticed I'm not getting S3 metrics. I see data for EC2, ELB, Elasticache, RDS, etc. If I go into the cloudwatch  console on AWS I can see S3 metrics. It just looks like the S3 numbers are not being pulled in.

 Here is my test cloudwatch.yml file:

---

region: us-east-1
metrics:
- aws_namespace: AWS/S3
  aws_metric_name: BucketSizeBytes
  aws_dimensions: [BucketName]
- aws_namespace: AWS/S3
  aws_metric_name: NumberOfObjects
  aws_dimensions: [BucketName]

**Comment by brian-brazil** [comment]
If you run the equivalent to the above using the AWS CLI does it work for you?

**Comment by garryknox** [comment]
If I run the following it works, although I have to provide a bucket name.

aws cloudwatch get-metric-statistics --metric-name BucketSizeBytes --namespace "AWS/S3" --start-time 2016-08-28T00:00:00Z --end-time 2016-08-29 --statistics Average --unit Bytes --region us-east-1 --dimensions Name=BucketName,Value=my-bucket-name Name=StorageType,Value=StandardStorage --period 3600 --output json

**Comment by brian-brazil** [comment]
So the list-metrics requests won't tell you the bucket names?

**Comment by garryknox** [comment]
I see all of my bucket names in list-metrics. 

I just mentioned it because in my cloudwatch.yml file I don't specify a bucket name.

**Comment by brian-brazil** [comment]
Does it work without the `--units`?

**Comment by garryknox** [comment]
Yes, it still works without the  --unit. It my case the output is the same since it defaults to bytes.

**Comment by brian-brazil** [comment]
The cloudwatch exporter uses a 10m range and 1m interval by default, your command has much more. Is that it?

**Comment by garryknox** [comment]
Looks like that might be the issue. 

I'm not sure how accurate the information I have but It looks like S3 metrics aren't real time. They may only be updated once a day. This may explain the time range behavior for get-metric-statistics. 

For example this time range which overlaps with midnight UTC works:
 --start-time 2016-08-29T23:59:59Z --end-time 2016-08-30T00:01:00Z

This time range returns nothing:
--start-time 2016-08-30T01:00:01Z --end-time 2016-08-30T23:59:00Z


I'm fine with getting results once a day I want long term growth beyond 2 weeks and not real time data. Is there anyway to change the default behavior for  S3 in the current cloudwatch exporter to support this?

**Comment by brian-brazil** [comment]
Yes, the range and period and configurable.

**Comment by garryknox** [comment]
Can you give me an example?

**Comment by rln-fw** [comment]
I'm wrestling with the same issue. I tried specifying range_seconds 172800, period_seconds 86400 as well as selecting a specific dimension - with no luck.

- aws_namespace: AWS/S3
  aws_metric_name: BucketSizeBytes
  aws_dimensions: [BucketName]
  aws_dimension_select:
    BucketName: [i-haz-a-bucket]
  range_seconds: 172800
  period_seconds: 86400

I't would be great if someone with working config for S3, RDS clusters and EC2 instances (and other setups) would add them to example.yml or the readme.

**Comment by garryknox** [comment]
Yeah, still waiting on a working S3 example.

Here are some RDS & EC2 examples that work for me.

- aws_namespace: AWS/RDS
  aws_metric_name: CPUUtilization
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/RDS
  aws_metric_name: DatabaseConnections
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]
 
- aws_namespace: AWS/RDS
  aws_metric_name: FreeableMemory
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]
 
- aws_namespace: AWS/RDS
  aws_metric_name: FreeStorageSpace
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]
 
- aws_namespace: AWS/RDS
  aws_metric_name: ReadIOPS
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]
 
- aws_namespace: AWS/RDS
  aws_metric_name: WriteIOPS
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]
 
- aws_namespace: AWS/RDS
  aws_metric_name: ReadLatency
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]
 
- aws_namespace: AWS/RDS
  aws_metric_name: WriteLatency
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]
 
- aws_namespace: AWS/RDS
  aws_metric_name: ReadThroughput
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]
 
- aws_namespace: AWS/RDS
  aws_metric_name: WriteThroughput
  aws_dimensions: [DBInstanceIdentifier]
  aws_statistics: [Average]

- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_statistics: [Average]

- aws_namespace: AWS/EC2
  aws_metric_name: DiskReadOps
  aws_dimensions: [InstanceId]
  aws_statistics: [Average]

- aws_namespace: AWS/EC2
  aws_metric_name: DiskWriteOps
  aws_dimensions: [InstanceId]
  aws_statistics: [Average]

- aws_namespace: AWS/EC2
  aws_metric_name: NetworkIn
  aws_dimensions: [InstanceId]
  aws_statistics: [Average]

- aws_namespace: AWS/EC2
  aws_metric_name: NetworkOut
  aws_dimensions: [InstanceId]
  aws_statistics: [Average]

**Comment by vacri** [comment]
I noticed that if I didn't include the dimension 'StorageType' in my awscli test command, that I got a null datapoint.

```
root@cathode:/etc/prometheus# aws cloudwatch get-metric-statistics --metric-name BucketSizeBytes --namespace "AWS/S3"  --region us-east-1 --dimensions Name=BucketName,Value=vacris-magic-bucket --statistics Average --start-time 2017-03-08T00:00:00Z --end-time 2017-03-09 --period 3600
{
    "Datapoints": [],
    "Label": "BucketSizeBytes"
}
root@cathode:/etc/prometheus# aws cloudwatch get-metric-statistics --metric-name BucketSizeBytes --namespace "AWS/S3"  --region us-east-1 --dimensions Name=BucketName,Value=vacris-magic-bucket Name=StorageType,Value=StandardStorage --statistics Average --start-time 2017-03-08T00:00:00Z --end-time 2017-03-09 --period 3600
{
    "Label": "BucketSizeBytes",
    "Datapoints": [
        {
            "Timestamp": "2017-03-08T00:00:00Z",
            "Unit": "Bytes",
            "Average": 2023930163.0
        }
    ]
}
```

Is cloudwatch-exporter using both BucketName and StorageType when requesting data? It looks like you get an empty return if you don't. I'm also noticing that I'm unable to get Cloudfront data (which has the dimension 'region: global' in addition to the distribution ID).

For either s3 or cloudfront, if I add the 'missing' dimension to the config, it doesn't help. It also doesn't help if I used the 'dimension_select' arg with either dimension, or if I add the range_seconds and period_seconds above.
```
- aws_namespace: AWS/S3
  aws_metric_name: BucketSizeBytes
  aws_dimensions: [BucketName, StorageType]
  aws_statistics: [Maximum]

- aws_namespace: AWS/Cloudfront
  aws_metric_name: 5xxErrorRate
  aws_dimensions: [DistributionId, Region]
  aws_dimension_select:
    DistributionId: [LIST, OF, DISTRIBUTION, IDS]
  aws_statistics: [Sum]
```

Neither of the above give me output. Other namespaces (ELB, RDS) work as expected (but are removed during the test run below)
```
root@cathode:/etc/prometheus$ curl localhost:9106/metrics
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 1.687591897
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total 66.0
```

**Comment by brian-brazil** [comment]
Those aren't equivalent queries, try passing both the bucketname and storagetype with dimension select.

**Comment by AndreaGiardini** [comment]
Same problem here, adding bucketname and storagetype does not help

```
- aws_namespace: AWS/S3                                                         
  aws_metric_name: BucketSizeBytes                                              
  aws_dimensions: [BucketName, StorageType]                                     
  aws_dimension_select:                                                         
      StorageType: [StandardStorage]                                            
  aws_statistics: [Average]             
```

**Comment by AndreaGiardini** [comment]
Returns correctly datapoints:
```
awscli cloudwatch get-metric-statistics --metric-name BucketSizeBytes --namespace "AWS/S3"  --region eu-central-1 --statistics Average --start-time 2017-04-23T00:00:00Z --end-time 2017-04-24T00:00:00Z --period 60 --dimensions Name=BucketName,Value=XXX Name=StorageType,Value=StandardStorage
```

Does not return anything:
```
region: eu-central-1
metrics:
- aws_namespace: AWS/S3
  aws_metric_name: BucketSizeBytes
  aws_dimensions: [BucketName, StorageType]
  aws_dimension_select:
    BucketName: [XXX]
    StorageType: [StandardStorage]
  aws_statistics: [Average]
```

They look the same to me. Am I missing something?

**Comment by AndreaGiardini** [comment]
Fixed... the missing parameter is `range_seconds: 86400` since the space for S3 buckets is exposed once a day

**Comment by vacri** [comment]
Sorry for the delay on getting back about my version of this issue.

I followed AndreaGiardini's lead and added the range_seconds, and it worked for me after tweaking, however I had to include both range_seconds and period_seconds - either one by itself didn't work (even when set to two days). Also, for me, range_seconds set to one day didn't work; I needed to set it to two days.

The following config worked for me:
```
- aws_namespace: AWS/S3
  aws_metric_name: BucketSizeBytes              # or NumberOfObjects
  aws_dimensions: [BucketName, StorageType]
  aws_dimension_select:
    BucketName: [my.awesome.bucket]
    Storage_Type: [StandardStorage]
  aws_statistics: [Maximum]
  range_seconds: 172800
  period_seconds: 86400
```

Also works if you take out the 'aws_dimension_select' section, and you'll get results for all buckets... however for our 70-odd buckets this adds about 22 seconds to the scrape...
