### ISSUE TITLE
Feature Request: Support Metric Math

### ISSUE THREAD

**Issue by sidewinder12s** [prometheus/cloudwatch_exporter#406]
This appears to be blocked by #134 & using the GetMetricData API. 

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html#metric-math-syntax

Some metrics are only available by computing them using Metric Math, like the actual value of Service Quotas.

```plain
(usage_data/SERVICE_QUOTA(usage_data))*100
```

The other popular cloudwatch_exporter has a similar feature request: https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/138

**Comment by matthiasr** [comment]
Thank you, I think that's a valid request, but it is a ways off as you noted. Given YACE is closer to having it, I would however encourage implementing it over there first.

**Comment by or-shachar** [comment]
@sidewinder12s  @matthiasr - now that we support `GetMetricData` - we might be just as close as YACE to metric math.

Our company doesn't use metric math so I'm not sure it's a priority for us to implement it but it might be worth talking about how we would want this feature to be used.

@sidewinder12s  - given our current configuration model - how would you change it to support metric math. IIUC - it'll need to support (ordered?) set of named expressions and a final expression. How would you accommodate it in the [CloudwatchExporter configuration](https://github.com/prometheus/cloudwatch_exporter#configuration)?

(It'll be very helpful if you could compose a desired example configuration).

**Comment by sidewinder12s** [comment]
Here is an example of what the Service Quota expression queries look like in CloudWatch (from the source view).

```json
{
    "metrics": [
        [ "AWS/Usage", "ResourceCount", "Class", "Standard/Spot", "Resource", "vCPU", "Service", "EC2", "Type", "Resource", { "id": "usage_data", "color": "#1f77b4", "stat": "Sum", "period": 300, "visible": false } ],
        [ { "expression": "(usage_data/SERVICE_QUOTA(usage_data))*100", "label": "% Utilization", "id": "pct_utilization", "color": "#1f77b4", "region": "us-east-1", "period": 60 } ]
    ],
    "view": "timeSeries",
    "region": "us-east-1",
    "title": "All Standard (A, C, D, H, I, M, R, T, Z) Spot Instance Requests - (Utilization %)",
    "stat": "Maximum",
    "period": 60
}
```

I am not super familiar with how complicated these kinds of queries can get. My nieve thought would be adding a new sub-dict that lets you have a primary query and then an expression query.

```yaml
- aws_namespace: AWS/Usage
  aws_metric_name: ResourceCount
  aws_dimensions: [Service, Resource, Type, Class]
  aws_dimension_select: 
    Service: EC2
    Resource: vCPU
    Type: Resource
    Class: Standard/Spot
  aws_expression:
    query: (queried_metric/SERVICE_QUOTA(queried_metric))*100
```

`queried_metric` might just need to be canned or maybe add another top level key of `label` similar to how the console does it.
