### ISSUE TITLE
Question: How to scrape only tagged s3 buckets?

### ISSUE THREAD

**Issue by szEvEz** [prometheus/cloudwatch_exporter#412]
Hi,

my issue currently is, that I only want to scrape a specific set of s3 buckets which are tagged with `monitoring: enabled`

My configuration is the following:

```yaml
    - aws_namespace: AWS/S3
      aws_dimensions: [BucketName, StorageType]
      aws_metric_name: BucketSizeBytes
      aws_statistics: [Average]
      range_seconds: 172800
      period_seconds: 86400
      set_timestamp: false
      aws_tag_select:
        tag_selections:
          monitoring: ["enabled"]
        resource_type_selection: "s3:bucket"
        resource_id_dimension: BucketName
```

After applying this configuration, I am not receiving any s3 related metrics anymore. Can someone push me into the right direction here? 

Thank you very much!

**Comment by matthiasr** [comment]
My read of [this page](https://docs.aws.amazon.com/AmazonS3/latest/userguide/cloudwatch-monitoring.html) is that the metrics are tagged based on _object_ tags, but not bucket tags. What happens if you tag the objects?

**Comment by sepich** [comment]
@szEvEz, this one works for me for bucket level tags:
`resource_type_selection: "s3:"`

**Comment by szEvEz** [comment]
I went now with the following solution

```yaml
    - aws_namespace: AWS/S3
      aws_dimensions: [BucketName, StorageType]
      aws_metric_name: BucketSizeBytes
      aws_statistics: [Average]
      range_seconds: 172800
      period_seconds: 86400
      set_timestamp: false
      aws_dimension_select_regex:
        BucketName: [my-buckets.*]
```

I've just made use of `aws_dimension_select_regex` and just filter for specific bucket names now.
