### ISSUE TITLE
use_get_metric_data not working with the latest version (0.14.0) of Cloudwatch Exporter 

### ISSUE THREAD

**Issue by sandeepnethi** [prometheus/cloudwatch_exporter#434]
Hi,

I was trying to evaluate this exporter and found that the experimental flag `use_get_metric_data` is not working as stated in the instructions and throwing below error when trying to call metrics endpoint. 

my exporter config is as below. I have double checked the syntax for this flag from the codebase and I don't see any issues. Please let me know what could be wrong here. 

```
region: us-east-1
metrics:
- aws_namespace: AWS/EC2
  use_get_metric_data: true
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_tag_select:
    resource_type_selection: ec2:instance
    resource_id_dimension: InstanceId
```

`java.lang.NoSuchMethodError: 'java.util.List java.util.stream.Stream.toList()'
at io.prometheus.cloudwatch.GetMetricDataDataGetter.buildStatsList(GetMetricDataDataGetter.java:50)
at io.prometheus.cloudwatch.GetMetricDataDataGetter.buildMetricDataQueries(GetMetricDataDataGetter.java:61)
at io.prometheus.cloudwatch.GetMetricDataDataGetter.buildMetricDataRequests(GetMetricDataDataGetter.java:127)
at io.prometheus.cloudwatch.GetMetricDataDataGetter.fetchAllDataPoints(GetMetricDataDataGetter.java:138)
at io.prometheus.cloudwatch.GetMetricDataDataGetter.<init>(GetMetricDataDataGetter.java:181)
at io.prometheus.cloudwatch.CloudWatchCollector.scrape(CloudWatchCollector.java:586)
at io.prometheus.cloudwatch.CloudWatchCollector.collect(CloudWatchCollector.java:690)
at io.prometheus.client.Collector.collect(Collector.java:46)
at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:197)
at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:212)
at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71)
at io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53)
at io.prometheus.client.servlet.common.exporter.Exporter.doGet(Exporter.java:75)
at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:52)`

Thanks,
