### ISSUE TITLE
Filter metrics based on tag

### ISSUE THREAD

**Issue by nlohiaTW** [prometheus/cloudwatch_exporter#445]
We have an autoscaling group in which each EC2 instance has a common tag. We need to fetch BurstBalance metric of the EBS volume attached to each of these instances. 
So far we have the below config.yml which fetches the BurstBalance metric of the volumeId:
```
region: eu-central-1
metrics:
- aws_dimensions:
   - VolumeId
  aws_dimension_select:
    VolumeId: [vol-asdf,vol-qwer]
  aws_metric_name: BurstBalance
  aws_namespace: AWS/EBS
  aws_statistics:
  - Average
```
We can see the corresponding VolumeId of the metric but we also want to see InstanceId of the node to which volume is attached. We have two questions:
1. Is it possible to have such configuration where we can see the instanceId along with the VolumeId and the metric? 
2. Is it possible to filter out based on the common tag attached on the EC2 instances (instead of hard-coding volume-Ids)?
