### ISSUE TITLE
AWS/SQS Metrics

### ISSUE THREAD

**Issue by mark-feinkind-avalara** [prometheus/cloudwatch_exporter#459]
I've added the following to our config.yml (taken from the examples), however, no metrics are being pulled within the metrics endpoint even though the cloudwatch metrics shows them:

```
  - aws_dimensions:
    - QueueName
    aws_metric_name: NumberOfMessagesSent
    aws_namespace: AWS/SQS
    aws_statistics:
    - Average
```

Could you provide some guidance as to how to resolve this?
