### ISSUE TITLE
[bug]: Unable to get AWS/ManagedBlockchain metrics

### ISSUE THREAD

**Issue by DavidSanchezAlvarez** [prometheus/cloudwatch_exporter#466]
### What did you do
I've aded the following configuration to CoudWatch_Exporter, regarding AWS/ManagedBlockchain metrics, and there is no way to make it work.

```
config: |-
  # This is the default configuration for prometheus-cloudwatch-exporter
  region: eu-west-1
  role_arn: arn:aws:iam::99999999999:role/role_prometheus
  period_seconds: 240
  metrics:
  ################# S3 ##################################
  - aws_namespace: AWS/S3
    aws_metric_name: BucketSizeBytes
    aws_dimensions: 
    - BucketName
    - StorageType
    aws_statistics: 
    - Average
    set_timestamp: false
    range_seconds: 172800
    period_seconds: 86400

  ################# Blockchain ##################################
  - aws_namespace: AWS/ManagedBlockchain
    aws_metric_name: Transactions
    aws_dimensions: [Channel, NodeId, MemberId, NetworkId]
    aws_statistics: 
    - Average
    set_timestamp: false
    range_seconds: 172800
    period_seconds: 86400        

  - aws_namespace: AWS/ManagedBlockchain
    aws_metric_name: 'CPU Utilization'
    aws_dimensions: [Channel, NodeId, MemberId, NetworkId]
    aws_statistics: []   

  - aws_namespace: AWS/ManagedBlockchain
    aws_metric_name: 'Memory Utilization'
    aws_dimensions: [Channel, NodeId, MemberId, NetworkId]
    aws_statistics: []

  - aws_namespace: AWS/ManagedBlockchain
    aws_metric_name: 'CPUUtilization'
    aws_dimensions: [Channel, NodeId, MemberId, NetworkId]
    aws_statistics: []   

  - aws_namespace: AWS/ManagedBlockchain
    aws_metric_name: 'MemoryUtilization'
    aws_dimensions: [Channel, NodeId, MemberId, NetworkId]
    aws_statistics: []  
```
The AWS/ManagedBlockchain metrics are duplicated with different  names and options in order to try to find a solution. The S3 bucket metris are retrieved with no issues. AWS/ManagedBlockchain metrics are available in CloudWatch and can bee seen directly from AWS portal.

### What did you expect to see?
I expect to get those metrics from CloudWatch.

### What did you see instead? Under which circumstances?
I see nothing, no metrics from AWS/ManagedBlockchain, only metrics from S3.

### Are you currently working around this issue?
I've tried many different combinations, and none was useful.

### Environment
* Exporter version: `0.12.2`
* Operating system & architecture: `AWS EKS` 
* Running in containers? yes
* Using the official image? yes
