### ISSUE TITLE
[bug]: Unable to access AWS/RDS BurstBalance metrics

### ISSUE THREAD

**Issue by r3kzi** [prometheus/cloudwatch_exporter#473]
### What did you do
```yaml
region: eu-central-1
warn_on_empty_list_dimensions: true
metrics:
- aws_namespace: AWS/RDS
  aws_metric_name: BurstBalance
  aws_dimensions:
    - DBInstanceIdentifier
```

```shell
$ aws cloudwatch list-metrics --metric-name BurstBalance --namespace AWS/RDS | jq ".Metrics[].Dimensions"
```

### What did you expect to see?
BurstBalance metrics in the same way like e.g. DatabaseConnections are exposed.

This works:
```yaml
region: eu-central-1
warn_on_empty_list_dimensions: true
metrics:
- aws_namespace: AWS/RDS
  aws_metric_name: DatabaseConnections
  aws_dimensions:
    - DBInstanceIdentifier
```

### What did you see instead? Under which circumstances?
```shell
$ docker run -p 9106:9106 -v $(pwd)/config.yml:/config/config.yml prom/cloudwatch-exporter
[....]
Dec 27, 2022 2:44:34 PM io.prometheus.cloudwatch.DefaultDimensionSource listDimensions
WARNING: (listDimensions) ignoring metric AWS/RDS:BurstBalance due to dimensions mismatch
``` 

### Environment
* Exporter version: 
```shell
$ curl -Ss http://localhost:9106/metrics  | grep cloudwatch_exporter_build_info       
cloudwatch_exporter_build_info{build_version="0.15.1",release_date="2022-10-25",} 1.0
```
* Operating system & architecture: `Linux x86_64 / Ubuntu`
* Running in containers? y
* Using the official image? y
