### ISSUE TITLE
Unable to scrape AWS/WAFV2 metrics using tags

### ISSUE THREAD

**Issue by peterpakos** [prometheus/cloudwatch_exporter#475]
I'm unable to scrape `AWS/WAFV2` metrics using the following config:

```
  - aws_dimensions:
    - Region
    - Rule
    - WebACL
    aws_metric_name: AllowedRequests
    aws_namespace: AWS/WAFV2
    aws_statistics:
    - Sum
    aws_tag_select:
      tag_selections:
        Env: ["uk"]
      resource_type_selection: "wafv2:regional/webacl"
      resource_id_dimension: WebACL
  - aws_dimensions:
    - Region
    - Rule
    - WebACL
    aws_metric_name: BlockedRequests
    aws_namespace: AWS/WAFV2
    aws_statistics:
    - Sum
    aws_tag_select:
      tag_selections:
        Env: ["uk"]
      resource_type_selection: "wafv2:regional/webacl"
      resource_id_dimension: WebACL
  - aws_dimensions:
    - Region
    - Rule
    - WebACL
    aws_metric_name: CountedRequests
    aws_namespace: AWS/WAFV2
    aws_statistics:
    - Sum
    aws_tag_select:
      tag_selections:
        Env: ["uk"]
      resource_type_selection: "wafv2:regional/webacl"
      resource_id_dimension: WebACL
```

Without `aws_tag_select` it works just fine:

```
  - aws_dimensions:
    - Region
    - Rule
    - WebACL
    aws_metric_name: AllowedRequests
    aws_namespace: AWS/WAFV2
    aws_statistics:
    - Sum
  - aws_dimensions:
    - Region
    - Rule
    - WebACL
    aws_metric_name: BlockedRequests
    aws_namespace: AWS/WAFV2
    aws_statistics:
    - Sum
  - aws_dimensions:
    - Region
    - Rule
    - WebACL
    aws_metric_name: CountedRequests
    aws_namespace: AWS/WAFV2
    aws_statistics:
    - Sum
```

The `Env` tag is set for `WebACL`:

```
aws wafv2 list-tags-for-resource --resource-arn arn:aws:wafv2:eu-west-2:xxx:regional/webacl/yyy/zzz
{
    "NextMarker": "",
    "TagInfoForResource": {
        "ResourceARN": "arn:aws:wafv2:eu-west-2:xxx:regional/webacl/yyy/zzz",
        "TagList": [
            {
                "Key": "Env",
                "Value": "uk"
            },
            {
                "Key": "Environment",
                "Value": "Production UK"
            },
            {
                "Key": "ManagedBy",
                "Value": "Terraform"
            }
        ]
    }
}
```

Any idea how to make it work with tags?
