### ISSUE TITLE
ability to add tags as metric labels

### ISSUE THREAD

**Issue by jeremydescamps** [prometheus/cloudwatch_exporter#476]
# Proposal
###  Use case. Why is this important?

I am cloudwatch-exporter with multi projects in the same AWS account.
I have several AWS resources, such as ELB that are tagged on the AWS side with `Project: A`, `Project: B` and so on.
Each ELB is dedicated to a specific project, so it is tagged with the `Project` tag.

Here's my cloudwatch-exporter configuration :

```yaml
    region: eu-west-3
    period_seconds: 300
    set_timestamp: false
    metrics:
    - aws_namespace: AWS/ApplicationELB
      aws_metric_name: UnHealthyHostCount
      aws_dimensions:
      - LoadBalancer
      - TargetGroup
      aws_statistics:
      - Average
```

So, with this configuration, my single instance of cloudwatch-exporter is able to retrieve `aws_applicationelb_un_healthy_host_count_average` metrics for all my ELB.

Here is an example of retrieval for this metric :

```
aws_applicationelb_un_healthy_host_count_average{container="prometheus-cloudwatch-exporter", endpoint="9106", exported_job="aws_applicationelb", instance="100.64.94.10:9106", job="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter", load_balancer="app/k8s-xxx-yyy-cc39906031/38d0f7cd1c384fcd", namespace="monitoring", pod="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter-78h9dr9", service="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter", target_group="targetgroup/k8s-xxx-yyy-34f497ba38/7c79fb79679d0f51"}
```

The problem I have is I am not able to identify the project for this metric.

It could be nice to export tags of the AWS resource within the metric.
Is this currently supported ?

I have also read about `aws_tag_select` from the documentation, and I tried something like this : 

```yaml
    region: eu-west-3
    period_seconds: 300
    set_timestamp: false
    metrics:
    - aws_namespace: AWS/ApplicationELB
      aws_metric_name: UnHealthyHostCount
      aws_dimensions:
      - LoadBalancer
      - TargetGroup
      aws_statistics:
      - Average
      aws_tag_select:
        tag_selections:
          Project: ["A", "B"]
        resource_type_selection: "elasticloadbalancing:"
        resource_id_dimension: LoadBalancerName
```

But from the doc, I didn't get the tip about `aws_resource_info`.
Here is an example of what I get when using the configuration with specified `aws_tag_select` : 

```
aws_resource_info{arn="arn:aws:elasticloadbalancing:eu-west-3:XXXXXXXXXX:listener-rule/app/k8s-xxx-yyy-8be4f31d11/1a0a8c03e69b5f60/684c64eaa8b18f3e/5914caff08676b6c", container="prometheus-cloudwatch-exporter", endpoint="9106", exported_job="aws_applicationelb", instance="100.64.94.10:9106", job="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter", load_balancer_name="app/k8s-yyy-xxx-8be4f31d11/1a0a8c03e69b5f60/684c64eaa8b18f3e/5914caff08676b6c", namespace="monitoring", pod="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter-78h9dr9", service="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter", tag_elbv2_k8s_aws_cluster="dev-cluster", tag_ingress_k8s_aws_resource="443:1", tag_Project="A"}
```

So yeah, here I am able to get my `Project` tag, but my `aws_applicationelb_un_healthy_host_count_average` metric keeps unchanged (without the `Project` tag).

Did I miss something ?

### How do you think the new configuration should look like?

It might be something like this to create label in metrics regarding AWS tags:

```yaml
    metrics:
    - aws_namespace: AWS/ApplicationELB
      aws_metric_name: UnHealthyHostCount
      aws_dimensions:
      - LoadBalancer
      - TargetGroup
      aws_statistics:
      - Average
      exported_tags:
      - Project
```

This might result in any `aws_applicationelb_un_healthy_host_count_average` metric to have `tag_Project` label.

Thanks a lot.
