### ISSUE TITLE
[bug]: inconsistency labels between ELB metrics and aws_resource_info metric

### ISSUE THREAD

**Issue by jeremydescamps** [prometheus/cloudwatch_exporter#477]
### What did you do
I am retrieving ELB metrics and want to add `project` tag from AWS ELB as label in ELB metrics.

So I read the documentation about `aws_tag_select` when retrieving metrics from CloudWatch, so here's my config : 

```yaml
    region: eu-west-3
    period_seconds: 300
    set_timestamp: false
    metrics:
    - aws_namespace: AWS/ApplicationELB
      aws_metric_name: UnHealthyHostCount
      aws_dimensions:
      - LoadBalancer
      - TargetGroup
      aws_statistics:
      - Average
      aws_tag_select:
        tag_selections:
          project: ["A", "B"]
        resource_type_selection: "elasticloadbalancing:"
        resource_id_dimension: LoadBalancerName
```

Here is what I get for both `aws_applicationelb_un_healthy_host_count_average` and `aws_resource_info`:

```
aws_applicationelb_un_healthy_host_count_average{container="prometheus-cloudwatch-exporter", endpoint="9106", exported_job="aws_applicationelb", instance="100.64.94.10:9106", job="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter", load_balancer="app/k8s-xx-yy-cc39906031/38d0f7cd1c384fcd", namespace="monitoring", pod="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter-78h9dr9", service="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter", target_group="targetgroup/k8s-xx-yy-34f497ba38/7c79fb79679d0f51"}

aws_resource_info{arn="arn:aws:elasticloadbalancing:eu-west-3:XXX:loadbalancer/app/k8s-d2c-m2oingre-cc39906031/38d0f7cd1c384fcd", container="prometheus-cloudwatch-exporter", endpoint="9106", exported_job="aws_applicationelb", instance="100.64.94.10:9106", job="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter", load_balancer_name="app/k8s-xx-yy-cc39906031/38d0f7cd1c384fcd", namespace="monitoring", pod="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter-78h9dr9", service="cloudwatch-exporter-qual-prometheus-cloudwatch-exporter", tag_project="yy/xx-ingress-events"}
```

Now I am trying to do the join operation to get the tag `project` within `aws_applicationelb_un_healthy_host_count_average` : 

```
aws_applicationelb_un_healthy_host_count_average * on(load_balancer) group_left(tag_project) aws_resource_info{}
```

But, this cannot work because my pivot label is `load_balancer` while `aws_resource_info` has `load_balancer_name` label, not `load_balancer`.

Both labels does not have the same name, the latest request cannot work !

In guess this is a bug.

Regards.
