### ISSUE TITLE
[bug]: discrepancy between exported size and actual size

### ISSUE THREAD

**Issue by Goateater94** [prometheus/cloudwatch_exporter#479]
Hello! I'm noticing problems with the BucketSizeBytes metric.
Specifically, the bucket size that is shown to me is much larger than the actual size I see from the AWS dash or CLI.
For example,the query
aws_s3_bucket_size_bytes_average{bucket_name="mybucket"} returns 13409425260 , approximately 13 GB.
From the AWS dashboard, on the other hand, I read that that bucket has a current size of 2.5 GB, the AWS CLI also confirms that size.
Am I doing something wrong?

### Environment
* Exporter version: `0.15.1`
* Operating system & architecture: 20.04.1-Ubuntu x86_64
* Running in containers? n
* Using the official image? 

### Exporter configuration file
<details>
<summary>
</summary>

```
region: eu-west-1


# Request data that spans this range:
#range_seconds: 120
# Request data that is already this old
delay_seconds: 60
# How often do we query AWS?
#  period_seconds: 120


#---------S3 SECTION-----------------
metrics:
 - aws_namespace: AWS/S3
   aws_metric_name: BucketSizeBytes
   aws_dimensions: [BucketName, StorageType]
   aws_statistics: [Average]
   range_seconds: 172800
   period_seconds: 86400
   set_timestamp: false

```
</details>
