### ISSUE TITLE
Can't specify region for a metric

### ISSUE THREAD

**Issue by gozer** [prometheus/cloudwatch_exporter#49]
Would be nice if it was possible, as I am trying to get at AWS/Billing metrics from a region different from us-east-1

I can easily run 2 cloudwatch_exporters, but wouldn't it be nice to be able to just do:
```
region: us-west-2
metrics:
  # ELB Metrics
- aws_namespace: AWS/ELB
  aws_metric_name: HealthyHostCount
  aws_dimensions: [LoadBalancerName]
  aws_statistics: [Average,Maximum]

  [...]

   # Billing is strange, only exists in us-east-1
 - aws_namespace: AWS/Billing
   region: us-east-1
   range_seconds: 21600
   aws_metric_name: EstimatedCharges
   aws_dimensions: [ServiceName,Currency]
   aws_dimension_select:
     Currency: [USD]
```
