### ISSUE TITLE
[metrics]: short description here

### ISSUE THREAD

**Issue by nandhainter** [prometheus/cloudwatch_exporter#529]
### Context information

* AWS service: Network ELB and application ELB
* CloudWatch namespace:
* Link to metrics documentation for this service:
* AWS region of the exporter: us-west-2
* AWS region of the service:

<details>
    <summary>
I am running exporter in a pod but I can't see Load balancer metrics in prometheus and shows no data point . </summary>

```yaml
#NLB
    - aws_namespace: AWS/NetworkELB
      aws_metric_name: UnHealthyHostCount
      aws_dimensions:	[LoadBalancer, TargetGroup]
      aws_statistics: [Minimum]
    #ELB
    - aws_namespace: AWS/ApplicationELB
      aws_metric_name: UnHealthyHostCount
      aws_dimensions:	[LoadBalancer, TargetGroup]
      aws_statistics: [Average]

Prometheus:

I am using below expressions to get the data but it shows no data point.

expr: aws_applicationelb_un_healthy_host_count_average offset 10m > 0
aws_networkelb_un_healthy_host_count_minimum offset 10m >0



```

</details>

<details>
    <summary>
       I don't see any logs in pod
    </summary>

```log

```
