### ISSUE TITLE
[metrics]: Unable to set the provided role while deploying in Kubernetes environment

### ISSUE THREAD

**Issue by abhisar007** [prometheus/cloudwatch_exporter#533]
### Context information
We are trying to deploy the cloudwatch exporter in EKS environment. When the deployment is successful, we see that scrape fails. As, it assumes the default cluster role and not the role with all permission provided in the values.yaml file during deployment.

I dont want to add the cloudwatch permission to the default cluster, as it is not recommended for production use. Please help if you came across similar issue. Any help is highly appreciated. I have added parts of my config.

* AWS service:
* CloudWatch namespace:
* Link to metrics documentation for this service:
* AWS region of the exporter:
* AWS region of the service:

<details>
    <summary>
        Exporter configuration
    </summary>

```yaml
aws:
  role: "arn:aws:iam::xx:role/xxx"
  # Enables usage of regional STS endpoints rather than global which is default
  stsRegional:
    enabled: false
  
secret:
    name: abcd
    
serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  #false
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "service_account_name"
  #default
  # annotations:
  # Will add the provided map to the annotations for the created serviceAccount
  # e.g.
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxx:role/xxxxx
    #eks.amazonaws.com/sts-regional-endpoints: "true"  
  # Specifies whether to automount API credentials for the ServiceAccount.
  automountServiceAccountToken: true

rbac:
  # Specifies whether RBAC resources should be created
  create: true


```

</details>

<details>
    <summary>
        Exporter logs
    </summary>

```log
software.amazon.awssdk.services.cloudwatch.model.CloudWatchException: User: arn:aws:sts::xxxxxxx:assumed-role/EKS/xxxxx is not authorized to perform: cloudwatch:ListMetrics because no identity-based policy allows the cloudwatch:ListMetrics action (Service: CloudWatch, Status Code: 403, Request ID: xxxxxxx)
```
