### ISSUE TITLE
Unnecessarily hard to override config file location.

### ISSUE THREAD

**Issue by rlnrln** [prometheus/cloudwatch_exporter#54]
The Dockerfile specifies the path to the config file as part of the entrypoint:

ENTRYPOINT [ "java", "-jar", "/cloudwatch_exporter.jar", "9106", "/config.yml" ]

I run kubernetes and would like to mount the config as a volume; however, I can't mount the volume on the root as that would make the rest of the file system unreadable. I could override the entrypoint in the location, but then I'd have to specify the entire entrypoint command.

- **Suggestion 1:** Use /etc/cloudwatch-exporter as the default path, analogous with other prometheus binaries.

- **Suggestion 2:** Move /config.yml to a CMD statement instead, so it can more easily be overridden in kubernetes 'args' config, ie:

    ENTRYPOINT [ "java", "-jar", "/cloudwatch_exporter.jar", "9106" ]
    CMD [ "/config.yml" ]

**Comment by gianrubio** [comment]
@rlnrln I had the same problem, overriding the `command` solve the issue. Otherwise I'm with you on move `config.yml` to another directory.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: cloudwatch-exporter
  name: cloudwatch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudwatch-exporter
  template:
    metadata:
      labels:
        app: cloudwatch-exporter
    spec:
      containers:
      - command:
        - java
        - -jar
        - /cloudwatch_exporter.jar
        - "9100"
        - /config/config.yml
        image: prom/cloudwatch-exporter
        imagePullPolicy: Always
        name: cloudwatch-exporter
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        volumeMounts:
        - mountPath: /config/
          name: vol-cloudwatch-exporter
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: cloudwatch-exporter
        name: vol-cloudwatch-exporter
```
