### ISSUE TITLE
[metrics]: can't get all s3 metrics

### ISSUE THREAD

**Issue by 80kk** [prometheus/cloudwatch_exporter#547]
In my configuration for S3 I have following:
```yaml
  - aws_namespace: AWS/S3
    aws_metric_name: 4xxErrors
    aws_dimensions: [BucketName, FilterId]
    aws_statistics: [Sum]
  - aws_namespace: AWS/S3
    aws_metric_name: 5xxErrors
    aws_dimensions: [BucketName, FilterId]
    aws_statistics: [Sum]
  - aws_namespace: AWS/S3
    aws_metric_name: AllRequests
    aws_dimensions: [BucketName, FilterId]
    aws_statistics: [Sum]
  - aws_namespace: AWS/S3
    aws_metric_name: BytesDownloaded
    aws_dimensions: [BucketName, FilterId]
    aws_statistics: [Sum, Average]
  - aws_namespace: AWS/S3
    aws_metric_name: BytesUploaded
    aws_dimensions: [BucketName, FilterId]
    aws_statistics: [Sum, Average]
  - aws_namespace: AWS/S3
    aws_metric_name: BucketSizeBytes
    aws_dimensions: [BucketName, StorageType]
    aws_statistics: [Average]
    range_seconds: 172800
    period_seconds: 86400
    set_timestamp: false
  - aws_namespace: AWS/S3
    aws_metric_name: NumberOfObjects
    aws_dimensions: [BucketName, StorageType]
    aws_statistics: [Average]
    range_seconds: 172800
    period_seconds: 86400
    set_timestamp: false
```
Unfortunately all I can get is `BucketSizeBytes` and `NumberOfObjects`. I've tried to change iteration over `aws_dimensions` or `aws_metric_name` as well as put these two metrics to the top of the list but with no luck.
