### ISSUE TITLE
[request]: Export Backup metrics

### ISSUE THREAD

**Issue by afreyermuth98** [prometheus/cloudwatch_exporter#566]
## Use case. Why is this important?

I would like to create dashboards from the backup metrics to check if all my backups and copies are working

## How do you think the new configuration should look like?

Example:

```yaml
- aws_dimensions:
  - BackupVaultName
  aws_metric_name: NumberOfBackupJobsCreated
  aws_namespace: AWS/Backup
  aws_statistics:
  - Sum
- aws_dimensions:
  - BackupVaultName
  aws_metric_name: NumberOfBackupJobsFailed
  aws_namespace: AWS/Backup
  aws_statistics:
  - Sum
- aws_dimensions:
  - BackupVaultName
  aws_metric_name: NumberOfBackupJobsCompleted
  aws_namespace: AWS/Backup
  aws_statistics:
  - Sum
- aws_dimensions:
  - BackupVaultName
  aws_metric_name: NumberOfCopyJobsCreated
  aws_namespace: AWS/Backup
  aws_statistics:
  - Sum
- aws_dimensions:
  - BackupVaultName
  aws_metric_name: NumberOfCopyJobsFailed
  aws_namespace: AWS/Backup
  aws_statistics:
  - Sum
- aws_dimensions:
  - BackupVaultName
  aws_metric_name: NumberOfCopyJobsCompleted
  aws_namespace: AWS/Backup
  aws_statistics:
  - Sum

```
