### ISSUE TITLE
[bug]:  Not able to fetch metrics when tagging enabled. 

### ISSUE THREAD

**Issue by shubhadaR** [prometheus/cloudwatch_exporter#574]
we tried to use AWS tag select feature However we only got aws_resource_info with tags but not aws resource metric.

  config.yaml

```yaml
region: ap-south-1
delay_seconds: 10
use_get_metric_data: false
metrics:
- aws_namespace: AWS/ELB
   use_get_metric_data: false
   aws_metric_name: RequestCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_tag_select:
     tag_selections:
       Monitoring: ["enabled"]
     resource_type_selection: "elasticloadbalancing:loadbalancer"
     resource_id_dimension: LoadBalancerName
   aws_statistics: [Sum]
- aws_namespace: AWS/ELB
   use_get_metric_data: false
   aws_metric_name: RequestCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_statistics: [Sum]

```

**Comment by klubi** [comment]
I believe I'm seeing similar issue with apigateway.

config:
```yaml
metrics:
  - aws_namespace: AWS/ApiGateway
    aws_metric_name: 5XX
    aws_statistics: [Sum]
    aws_dimensions: [ApiId]
    aws_tag_select:
      tag_selections:
        Product: ["ABC"]
      resource_type_selection: "apigateway:apis"
      resource_id_dimension: ApiId
```

Then only `aws_resource_info` metric is returned. But that metric seems to have incorrect api_id label.
Because it does not have only api gateway Id as value, but also `apis` prefix:

```
aws_resource_info{job="aws_apigateway",instance="",arn="arn:aws:apigateway:us-east-1::/apis/XXX",api_id="apis/XXX",tag_Product="ABC"} 1.0
```
