### ISSUE TITLE
polling frequency

### ISSUE THREAD

**Issue by otakup0pe** [prometheus/cloudwatch_exporter#58]
I don't seem to see any configuration for the polling frequency. Is this something which is actually modifiable? If not, is this the sort of pull request that would be welcome?

**Comment by AnthonyWC** [comment]
I think that's defined under prometheus configuration, e.g.

```
  - job_name: 'cloudwatch'
    static_configs:
      - targets: ['cloudwatch:9106']
    scrape_interval: 3m
    scrape_timeout: 1m
```
