### ISSUE TITLE
ConsumedLCUs is not being picked up by Prometheus Cloidwatch Exporter running inside a pod

### ISSUE THREAD

**Issue by mgk-123** [prometheus/cloudwatch_exporter#587]
### Context information

* AWS service: AWS Application Load Balancer
* CloudWatch namespace: AWS/ApplicationELB
* Link to metrics documentation for this service: 
* AWS region of the exporter:All Regions
* AWS region of the service: All Regions

```yaml
   aws_namespace: AWS/ApplicationELB
    aws_metric_name: ConsumedLCUs
    aws_statistics: Sum




```

</details>

<details>
    <summary>
        Exporter logs
    </summary>

```log

```

### What do you expect to happen?

Consumed LCU metric should be emitted by pod even when it it available in cloudwatch metrics console.Rest all metrics are available
### What happened instead?

Consumed LCU metric is not being  emitted by pod when it it available in cloudwatch metrics console.Rest all metrics are available
