### ISSUE TITLE
[metrics]:  AWS/SNS: Metrics NumberOfNotificationsDelivered/NumberOfNotificationsFailed do not get exported

### ISSUE THREAD

**Issue by danielrolfes2307** [prometheus/cloudwatch_exporter#596]
### Context information

* AWS service: SNS
* CloudWatch namespace: AWS/SNS
* Link to metrics documentation for this service:  https://docs.aws.amazon.com/sns/latest/dg/sns-monitoring-using-cloudwatch.html
* AWS region of the exporter: eu-central-1
* AWS region of the service: eu-central-1

<details>
    <summary>
        Exporter configuration
    </summary>

```yaml
  ###############################################
  # SNS metrics
  ###############################################
  - aws_namespace:   AWS/SNS
    aws_metric_name: NumberOfNotificationsDelivered
    aws_dimensions:  [TopicName,PhoneNumber]
    aws_statistics: [Sum]
    set_timestamp: false
  - aws_namespace:   AWS/SNS
    aws_metric_name: NumberOfNotificationsFailed
    aws_dimensions:  [TopicName,PhoneNumber]
    aws_statistics: [Sum,Average]
    set_timestamp: false
  - aws_namespace:   AWS/SNS
    aws_metric_name: NumberOfMessagesPublished
    aws_dimensions:  [TopicName]
    aws_statistics: [Sum]
    set_timestamp: false
  - aws_namespace:   AWS/SNS
    aws_metric_name: PublishSize
    aws_dimensions:  [TopicName]
    set_timestamp: false

```

</details>

<details>
    <summary>
        Exporter logs
    </summary>

```log

```
</details>

### What do you expect to happen?

"NumberOfNotificationsDelivered" and "NumberOfNotificationsFailed" should be exported.

### What happened instead?
Although I get datapoints in Cloudwatch metrics for "NumberOfNotificationsDelivered" and "NumberOfNotificationsFailed" they do not  show up when calling metrics-endpoint of cloudwatch-exporter via: curl localhost:9095/metrics

Metrics "NumberOfMessagesPublished" and "PublishSize" DO show up though.
