### ISSUE TITLE
ES metrics not appearing

### ISSUE THREAD

**Issue by evollusion** [prometheus/cloudwatch_exporter#60]
Hi - I am using the following config point, but see nothing for the ES metrics appearing when calling the metrics URL.

```
- aws_namespace: AWS/ES
      aws_metric_name: Nodes
      aws_dimensions: [ClientId, DomainName]
      aws_dimension_select:
        ClientId: [ 123456789 ]
        DomainName: [ myEsDomain ]
      aws_statistics: [ SampleCount ]
      period_seconds: 3600
```

I can query the metrics via aws cli, but using the same detail in the config still doesn't net anything.

Am I missing something or is this possibly a AWS issue?  I am currently successfully pulling EC2 and RDS metrics.

**Comment by brian-brazil** [comment]
It's probably the high period secs that's the issue. Leave it as the default, or bump range_seconds to fit.

**Comment by evollusion** [comment]
I seem to have managed to solve it, i would appear that the configuration must include and exclude dimensions and dimension_selects and these are not the same for each namespace.  The below config is now working as is the ELB one.  Thanks for the assist

- aws_namespace: AWS/ES
      aws_metric_name: ClusterStatus.red
      aws_dimensions: [ClientId, DomainName]
      aws_statistics: [ Minimum ]

**Comment by kaspernissen** [comment]
@evollusion I tried your solution without any success. 

I tried with, without, and a combination of period_seconds and range_seconds without any lock, as well as tweaking the values. I checked with the same credentials fetching metrics from RDS which is working fine. Further tried to verify that it wasn't anything specific with AWS ES. I was able to received metrics using the aws cli.

Here is my config. 
```
- aws_namespace: AWS/ES
  aws_metric_name: Nodes
  aws_dimensions: [ClientId, DomainName]
  aws_dimension_select:
    ClientId: [12345678]
    DomainName: [elasticsearch]
  aws_statistics: [Minimum]
```

Tried to inspect the code, and it looks like the `for (List<Dimension> dimensions: getDimensions(rule))´ in the scrape method is returning 0 objects. Which would result in datapoints not being fetched from what I can see.

**Comment by kaspernissen** [comment]
There seems to be an issue when specifying ClientId and DomainName, leaving these values out, as pointed out by @evollusion seems to work, however, you will fetch all values for all your es domains. But it's better than nothing.

**Comment by evollusion** [comment]
Yup, that is what I found.  What I am doing is using the domain label in my query to reduce what is returned and to configure the alarms and graphics correctly.

**Comment by rdtr** [comment]
Hmm, just curious why it happens...

**Comment by avinson** [comment]
@brian-brazil fyi, this appears to be a legitimate bug (not related to period setting). perhaps either re-open this issue or else add something to the docs that `aws_dimension_select` does not work with `AWS/ES` namespace? thanks for your help as always.

**Comment by brian-brazil** [comment]
I've yet to see anything here that's a potential bug in the cloudwatch exporter.

**Comment by willemveerman** [comment]
There are two sets of metrics in the `AWS/ES` ns: 
 - one set which can be filtered based on `ClientId` and `DomainName` - these are labelled "Per-Domain, Per-Client Metrics" in the AWS console
 - another set which can be filtered on `ClientId`, `DomainName` and `NodeId`

The first set are more broad and less granular; in general they cover the cluster as a whole rather than a specific node

I found that I needed to choose both `ClientId` and `DomainName` in `aws_dimensions` in order to access the 79 metrics in the former group, but when I did this I was able to filter based on domain name only.

Here's the config that worked for me:

```
      - aws_namespace: AWS/ES
        aws_metric_name: KNNCircuitBreakerTriggered
        aws_dimensions: [ClientId, DomainName]
        aws_dimension_select:
          DomainName: [domain-a,domain-b]
        aws_statistics: [Average]
      - aws_namespace: AWS/ES
        aws_metric_name: AlertingIndexExists
        aws_dimensions: [ClientId, DomainName]
        aws_dimension_select:
          DomainName: [domain-a,domain-b]
        aws_statistics: [Average]
     - etc...
````
