### ISSUE TITLE
[metrics]: How to use `use_get_metric_data`?

### ISSUE THREAD

**Issue by victoramsantos** [prometheus/cloudwatch_exporter#618]
### Context information

I'm in a situation where we can't ask AWS to increase our quota anymore (we are already on 300 rps). We thought that changing from `GetMetricStatistics` to `GetMetricData` would reduce the API burn. However we saw that we are already using the flag `use_get_metric_data` like 
```
region: {{REGION}}
delay_seconds: 300
use_get_metric_data: true <- HERE
metrics:
  - aws_namespace: AWS/DynamoDB
    aws_metric_name: ProvisionedWriteCapacityUnits
    aws_dimensions: [TableName]
    aws_dimension_select_regex:
      TableName: ["ABC"]
    aws_statistics: [Average]
...
```
I think as a global flag. However I could see in various issues in this repository people using it directly through the metric itself and I didn't find any doc explaining where to use it. 
**So my doubt is if we are effectively using it. Can some one help with this?**
