### ISSUE TITLE
[metrics]: AWS/PrivateLinkService can't get metric data 

### ISSUE THREAD

**Issue by huoshuaibing** [prometheus/cloudwatch_exporter#619]
### Context information

* AWS service:
* CloudWatch namespace: AWS/PrivateLinkService
* Link to metrics documentation for this service:
* AWS region of the exporter: ap-northeast-1
* AWS region of the service:

<details>
    <summary>
        Exporter configuration
    </summary>

```yaml
-aws_dimensions:
  - ServiceId
  aws_metrics_name: EndpointsCount
  aws_namespace: AWS/PrivateLinkServices
  aws_statistics:
  - Maximum




```

</details>

<details>
    <summary>
        Exporter logs
    </summary>

```log

```

**Comment by matthiasr** [comment]
Could you please show us what `aws cloudwatch list-metrics --namespace AWS/PrivateLinkServices` is for you?

One thing I find suspicious is that [the documentation](https://docs.aws.amazon.com/vpc/latest/privatelink/privatelink-cloudwatch-metrics.html) lists the dimension as `Service Id` (with a space), but I cannot see what it's like in actual CloudWatch because I don't use PrivateLink.

**Comment by huoshuaibing** [comment]
@matthiasr 
Yes, the dimension is  **Service Id**
![截屏2024-03-07 11 09 23](https://github.com/prometheus/cloudwatch_exporter/assets/23443116/e1e1c5ba-b2e1-47fe-bd80-4b9b193e78e2)

**Comment by fstr** [comment]
I'm using a space in the dimension `"Service Id"` and it works for me:

```yaml
    - aws_namespace: AWS/PrivateLinkServices
      aws_metric_name: EndpointsCount
      aws_dimensions: ["Service Id"]
      aws_tag_select:
        tag_selections:
          foo: ["bar"]
        resource_type_selection: ec2:vpc-endpoint-service
        resource_id_dimension: "Service Id"
      aws_statistics: [Average, Maximum, Sum]
```
