### ISSUE TITLE
An issue gathering metrics from SQL queues

### ISSUE THREAD

**Issue by jjuarez** [prometheus/cloudwatch_exporter#65]
After configure a bunch of SQL metrics (ApproximateNumberOfMessagesVisible) for some queues, trying to recover these metrics, our Prometheus server show this message as a result of the CloudWatch exporter:

text format parsing error in line 54: second HELP line for metric name "aws_sqs_approximate_number_of_messages_visible_sum"

Here's a sample of these metrics
```
 53 aws_sqs_approximate_number_of_messages_visible_sum{job="aws_sqs",instance="",queue_name="provisioning-notify-queue-protesis",} 0.0
 54 # HELP aws_sqs_approximate_number_of_messages_visible_sum CloudWatch metric AWS/SQS ApproximateNumberOfMessagesVisible Dimensions: [QueueName] Statistic: Sum Unit: Count
 55 # TYPE aws_sqs_approximate_number_of_messages_visible_sum gauge
```

and here's a snippet of the metric configuration file:
```yaml
 - aws_namespace: AWS/SQS
  aws_metric_name: ApproximateNumberOfMessagesVisible
  aws_dimensions:
  - QueueName
  aws_dimension_select:
    SQSName:
    - survela-provisioning-notify
    - survela-provisioning-check
  aws_statistics:
  - Sum
- aws_namespace: AWS/SQS
  aws_metric_name: ApproximateNumberOfMessagesVisible
  aws_dimensions:
  - QueueName
  aws_dimension_select:
    SQSName:
    - provisioning-notify-queue-pro
    - provisioning-check-queue-pro
  aws_statistics:
  - Sum
```
any help would be fantastic, thanks in advance
