### ISSUE TITLE
[metrics]: AWS/Connect metrics not appearing in Grafana

### ISSUE THREAD

**Issue by meridius01** [prometheus/cloudwatch_exporter#654]
### Context information

* AWS service: Amazon Connect
* CloudWatch namespace: AWS/Connect
* Link to metrics documentation for this service:  https://docs.aws.amazon.com/connect/latest/adminguide/monitoring-cloudwatch.html
* AWS region of the exporter: ap-southeast-1
* AWS region of the service: ap-southeast-2

<details>
    <summary>
        Exporter configuration
    </summary>

```yaml
  - aws_metric_name: ConcurrentCalls
    aws_dimensions: [InstanceId]
    aws_namespace: AWS/Connect
    aws_statistics: [Average]
```

</details>

<details>
    <summary>
        Exporter logs
    </summary>

```log

```

### What do you expect to happen?

I just want to have at least ConcurrentCalls to appear on Grafana for monitoring

### What happened instead?

The problem is that even I have the right format and settings (including the right IAM role with right permission and trust relationship), I can't see the specific metric of concern in Grafana when Cloudwatch Export was running.
