### ISSUE TITLE
Configured metrics not being scraped

### ISSUE THREAD

**Issue by duallain** [prometheus/cloudwatch_exporter#66]
I'm using a configuration that looks like the attached exhibit 1 below, and get back the metrics in exhibit 2.  The lambda and dynamo metrics are missing.  I would expect that the logs would show why the metrics are not being gathered, but there is no further information.

Why is this config breaking?  

What part of the code would you add logging to, so that it's easier to fix broken configs in the future?  
I'd happily submit a PR, but have no idea where to start.

Exhibit 1:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-config
data:
  config.yml: |
    region: us-west-2
    metrics:
    - aws_namespace: AWS/Lambda
      aws_metric_name: Errors
      aws_dimensions: [FunctionName, Resource, Version, Alias]
      aws_statistics: [Count]

    - aws_namespace: AWS/Lambda
      aws_metric_name: "Dead Letter Error"
      aws_dimensions: [FunctionName, Resource, Version, Alias]
      aws_statistics: [Count]

    - aws_namespace: AWS/Lambda
      aws_metric_name: Throttles
      aws_dimensions: [FunctionName, Resource, Version, Alias]
      aws_statistics: [Count]

    - aws_namespace: AWS/Lambda
      aws_metric_name: Duration
      aws_dimensions: [FunctionName, Resource, Version, Alias]
      aws_statistics: [Milliseconds]

    - aws_namespace: AWS/ES
      aws_metric_name: FreeStorageSpace
      aws_dimensions: [DomainName, ClientId]
      aws_statistics: [Minimum]

    - aws_namespace: AWS/ES
      aws_metric_name: SearchableDocuments
      aws_dimensions: [DomainName, ClientId]
      aws_statistics: [Sum, Minimum, Maximum]

    - aws_namespace: AWS/ES
      aws_metric_name: CPUUtilization
      aws_dimensions: [DomainName, ClientId]
      aws_statistics: [Maximum, Average]

    - aws_namespace: AWS/ES
      aws_metric_name: "ClusterStatus.yellow"
      aws_dimensions: [DomainName, ClientId]
      aws_statistics: [Minimum, Maximum]

    - aws_namespace: AWS/ES
      aws_metric_name: "ClusterStatus.red"
      aws_dimensions: [DomainName, ClientId]
      aws_statistics: [Minimum, Maximum]

    - aws_namespace: AWS/DynamoDB
      aws_metric_name: ReadThrottleEvents
      aws_dimensions: [TableName, GlobalSecondaryIndexName]
      aws_statistics: [Sum, SampleCount]
```

Exhibit 2:
```
 HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total 81855.0
# HELP aws_es_free_storage_space_minimum CloudWatch metric AWS/ES FreeStorageSpace Dimensions: [DomainName, ClientId] Statistic: Minimum Unit: Megabytes
# TYPE aws_es_free_storage_space_minimum gauge
aws_es_free_storage_space_minimum{job="aws_es",instance="",domain_name="es-hp-id-dev-us-west-2",client_id="871386769552",} 212726.246
# HELP aws_es_searchable_documents_sum CloudWatch metric AWS/ES SearchableDocuments Dimensions: [DomainName, ClientId] Statistic: Sum Unit: Count
# TYPE aws_es_searchable_documents_sum gauge
aws_es_searchable_documents_sum{job="aws_es",instance="",domain_name="es-hp-id-dev-us-west-2",client_id="871386769552",} 1.2435096795E10
# HELP aws_es_searchable_documents_minimum CloudWatch metric AWS/ES SearchableDocuments Dimensions: [DomainName, ClientId] Statistic: Minimum Unit: Count
# TYPE aws_es_searchable_documents_minimum gauge
aws_es_searchable_documents_minimum{job="aws_es",instance="",domain_name="es-hp-id-dev-us-west-2",client_id="871386769552",} 1.243503844E9
# HELP aws_es_searchable_documents_maximum CloudWatch metric AWS/ES SearchableDocuments Dimensions: [DomainName, ClientId] Statistic: Maximum Unit: Count
# TYPE aws_es_searchable_documents_maximum gauge
aws_es_searchable_documents_maximum{job="aws_es",instance="",domain_name="es-hp-id-dev-us-west-2",client_id="871386769552",} 1.24351936E9
# HELP aws_es_cpuutilization_maximum CloudWatch metric AWS/ES CPUUtilization Dimensions: [DomainName, ClientId] Statistic: Maximum Unit: Percent
# TYPE aws_es_cpuutilization_maximum gauge
aws_es_cpuutilization_maximum{job="aws_es",instance="",domain_name="es-hp-id-dev-us-west-2",client_id="871386769552",} 6.0
# HELP aws_es_cpuutilization_average CloudWatch metric AWS/ES CPUUtilization Dimensions: [DomainName, ClientId] Statistic: Average Unit: Percent
# TYPE aws_es_cpuutilization_average gauge
aws_es_cpuutilization_average{job="aws_es",instance="",domain_name="es-hp-id-dev-us-west-2",client_id="871386769552",} 4.714285714285714
# HELP aws_es_cluster_status_yellow_minimum CloudWatch metric AWS/ES ClusterStatus.yellow Dimensions: [DomainName, ClientId] Statistic: Minimum Unit: Count
# TYPE aws_es_cluster_status_yellow_minimum gauge
aws_es_cluster_status_yellow_minimum{job="aws_es",instance="",domain_name="es-hp-id-dev-us-west-2",client_id="871386769552",} 0.0
# HELP aws_es_cluster_status_yellow_maximum CloudWatch metric AWS/ES ClusterStatus.yellow Dimensions: [DomainName, ClientId] Statistic: Maximum Unit: Count
# TYPE aws_es_cluster_status_yellow_maximum gauge
aws_es_cluster_status_yellow_maximum{job="aws_es",instance="",domain_name="es-hp-id-dev-us-west-2",client_id="871386769552",} 0.0
# HELP aws_es_cluster_status_red_minimum CloudWatch metric AWS/ES ClusterStatus.red Dimensions: [DomainName, ClientId] Statistic: Minimum Unit: Count
# TYPE aws_es_cluster_status_red_minimum gauge
aws_es_cluster_status_red_minimum{job="aws_es",instance="",domain_name="es-hp-id-dev-us-west-2",client_id="871386769552",} 0.0
# HELP aws_es_cluster_status_red_maximum CloudWatch metric AWS/ES ClusterStatus.red Dimensions: [DomainName, ClientId] Statistic: Maximum Unit: Count
# TYPE aws_es_cluster_status_red_maximum gauge
aws_es_cluster_status_red_maximum{job="aws_es",instance="",domain_name="es-hp-id-dev-us-west-2",client_id="871386769552",} 0.0
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 0.382327836
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
```
