### ISSUE TITLE
Lots of requests for simple metrics

### ISSUE THREAD

**Issue by Rudd-O** [prometheus/cloudwatch_exporter#70]
We get these:

```yaml
---
region: ap-southeast-1
metrics:
 - aws_namespace: AWS/ECS
   aws_metric_name: CPUUtilization
   aws_dimensions: [ClusterName, ServiceName]
   aws_statistics: [SampleCount, Sum, Minimum, Maximum, Average]
 - aws_namespace: AWS/ECS
   aws_metric_name: MemoryUtilization
   aws_dimensions: [ClusterName, ServiceName]
   aws_statistics: [SampleCount, Sum, Minimum, Maximum, Average]
 - aws_namespace: AWS/ECS
   aws_metric_name: CPUReservation
   aws_dimensions: [ClusterName]
   aws_statistics: [Average]
 - aws_namespace: AWS/ECS
   aws_metric_name: MemoryReservation
   aws_dimensions: [ClusterName]
   aws_statistics: [Average]
```

This causes 58 requests upon every scrape.

Is there no way these can be batched?
