### ISSUE TITLE
[metrics]: Metrics are no longer pulled when using aws_tag_select

### ISSUE THREAD

**Issue by lukayeh** [prometheus/cloudwatch_exporter#713]
### Context information
* AWS service: AmazonMQ & Amazon MSK
* CloudWatch namespace: AWS/AmazonMQ & AWS/Kafka
* Link to metrics documentation for this service: n/a
* AWS region of the exporter: eu-central-1
* AWS region of the service: eu-central-1

When running Cloudwatch exporter with `aws_tag_select` enabled for services like RDS and Elasticache I get metrics returned, however when doing the same for MSK and MQ it does not return any metrics.

We know this works
```
    region: eu-central-1
    period_seconds: 60
    metrics:
    - aws_namespace: AWS/AmazonMQ
      aws_metric_name: MessageCount
      aws_dimensions:
        - Broker
      aws_statistics:
        - Sum
```

This does not:
```
    metrics:
    - aws_namespace: AWS/AmazonMQ
      aws_metric_name: MessageCount
      aws_dimensions:
        - Broker
      aws_statistics:
        - Sum
	  aws_tag_select:
	    tag_selections: 
	      Project: []
	    resource_type_selection: "mq:broker"
	    resource_id_dimension: [Broker]
```

This also does not work ❌:
```
    region: eu-central-1
    period_seconds: 60
    metrics:
    - aws_namespace: AWS/AmazonMQ
      aws_metric_name: MessageCount
      aws_dimensions:
        - Broker
      aws_statistics:
        - Sum
      aws_tag_select:
        tag_selections:
          Project: ["legit_tag"]
        resource_type_selection: "mq:broker"
        resource_id_dimension: "Broker"
```

For Kafka I've tried this but this also refuses to retrieve metrics:
```
  - aws_namespace: AWS/Kafka
    aws_metric_name: CpuCreditUsage
    aws_dimensions:
      - Cluster Name
    aws_statistics:
      - Average
    aws_tag_select:
      tag_selections: 
          Project: []
      resource_type_selection: "kafka:cluster"
      resource_id_dimension: "Cluster Name"
```

</details>

<details>
    <summary>
        Exporter logs
    </summary>

```log
WARNING: (listDimensions) ignoring metric AWS/AmazonMQ:MessageCount due to dimensions mismatch
```

### What do you expect to happen?

Metrics return when using `aws_tag_select`

### What happened instead?

No metrics are returned due to `dimensions mismatch`
