### ISSUE TITLE
[bug]: Duplicated metric data values

### ISSUE THREAD

**Issue by peterpakos** [prometheus/cloudwatch_exporter#746]
### What did you do

We are scraping custom CloudWatch metrics coming from Artillery.

Configuration snippet:

```
region: eu-west-2
role_arn: arn:aws:iam::xxx:role/grafana
delay_seconds: 0
use_get_metric_data: true
metrics:
  - aws_namespace: PerformanceTesting
    aws_metric_name: "http.requests"
    aws_dimensions: [Name, Test]
    aws_statistics: [Sum]
```

Metric data shown in CloudWatch UI:

![image](https://github.com/user-attachments/assets/44fb1dbd-c37d-4a48-8b6b-25965190907d)

Metric data returned from CloudWatch API:

```
{
    "MetricDataResults": [
        {
            "Id": "m1",
            "Label": "http.requests",
            "Timestamps": [
                "2024-09-24T12:31:00+00:00",
                "2024-09-24T12:30:00+00:00"
            ],
            "Values": [
                16.0,
                44.0
            ],
            "StatusCode": "Complete"
        }
    ],
    "Messages": []
}
```

### What did you expect to see?

Prometheus metrics in Grafana matching metrics in CloudWatch.

### What did you see instead? Under which circumstances?

First 2 data points matching CloudWatch then the last value repeated for 5-10 minutes.

Metric data in Grafana:

![image](https://github.com/user-attachments/assets/6f31e0c2-e7ca-4dcc-a1c5-468790bea80a)

![image](https://github.com/user-attachments/assets/3b084305-47c4-4b44-a6a0-73a8d18bb401)

### Are you currently working around this issue?

No

### Environment

```
# docker images | grep cloudwatch-exporter
prom/cloudwatch-exporter             latest    70a238bc9c70   5 weeks ago     297MB
```
