### ISSUE TITLE
example conf for AWS Glue

### ISSUE THREAD

**Issue by sivasankarig** [prometheus/cloudwatch_exporter#757]
## Use case. Why is this important?

  Could you create some example for AWS Glue job metrics ?

## How do you think the new configuration should look like?

Example:

```
region: us-east-1
metrics:
- aws_dimensions:
  - Type
  - JobRunId
  - JobName
  aws_metric_name: glue.2.jvm.heap.used
  aws_namespace: AWS/Glue
  aws_statistics:
  - Sum

```
