### ISSUE TITLE
[bug]: The Cloudfront metric data is inconsistent with the original metric data of Cloudwatch(采集到的cloudfront指标数据和原始数据不一致)

### ISSUE THREAD

**Issue by hucongwei** [prometheus/cloudwatch_exporter#761]
## 问题描述
- 通过YACE和Cloudwatch-Exporter采集到的Cloudfront指标数据和Cloudwatch原始指标数据不一致，Prometheus监控数据准确性受影响；

## Problem description
- The Cloudfront indicator data collected by YACE and Cloudwatt-Exporter are inconsistent with the original indicator data of Cloudwatch, and the accuracy of Prometheus monitoring data is affected.

### 监控数据链路：
- cloudfront -> cloudwatch -> YACE|Node-Exporter -> Prometheus - Grafana 

### Monitoring data link:
- Cloudwatch（Cloudfront metrics）-> YACE|Node-Exporter -> Prometheus -> Grafana

### 监控数据采样对比：
- 以分发E1ADYLIWRYAZZC的请求数指标为例
- 指标名称：aws_cloudfront_requests_sum 统计时长：1分钟、统计纬度：sum
- 取监控数据相邻两个值

### Monitoring data sampling comparison:
- The number of requests for distributing E1ADYLIWRYAZZC is used as an example
- Indicator name: aws_cloudfront_requests_sum Statistical duration: 1 minute, statistical latitude: sum
- Set two adjacent values of monitoring data

| time                  | cloudwatch | cloudwatch-exporter | YACE    |
|----------------------|------------|---------------------|---------|
| 2024-10-25 03:00 UTC | 814,552    | 733,830             | 193,375 |
|                      |            | 829757              | 132,084 |
| 2024-10-25 06:49 UTC | 314,435    | 254,827             | 254,827 |
|                      |            | 207,166             | 207,166 |

#### YACE
```

配置文件(config files)：
---# cat yace-cdn.yaml
apiVersion: v1alpha1
sts-region: us-east-1
discovery:
  jobs:
  - type: AWS/CloudFront
    regions: 
    - us-east-1
    searchTags:
    - key: env
      value: prod
    - key: project
      value: "^amp$"
    customTags:
    - key: app
      value: cdn
    - key: project
      value: "amp"
    dimensionNameRequirements:
    - DistributionId
    - Region
    period: 60
    length: 120
    metrics: 
      - name: 4xxErrorRate
        statistics: [Average]
      - name: 5xxErrorRate
        statistics: [Average]
      - name: TotalErrorRate
        statistics: [Average]
      - name: Requests
        statistics: [Sum]
启动命令(startup)：
su p7 -c 'cd /apps/yace && ./yace --listen-address :9120 --scraping-interval 60 --config.file ./yace-cdn.yaml 1>./yace-cdn.log 2>&1' &

```

#### Cloudwatch-exporter
```

配置文件(config files)：
---# cat cloudwatch-metrics-p7-cdn.yml
---
region: us-east-1
delay_seconds: 60
metrics:
#CloudFront cloudwatch-exporter metrics
 - aws_namespace: AWS/CloudFront
   aws_metric_name: 4xxErrorRate
   aws_statistics: [Average]
   aws_dimensions: [DistributionId,Region]
   aws_dimension_select:
     DistributionId: ["E1ADYLIWRYAZZC"]
     Region: ["Global"]
 - aws_namespace: AWS/CloudFront
   aws_metric_name: 5xxErrorRate
   aws_statistics: [Average]
   aws_dimensions: [DistributionId,Region]
   aws_dimension_select:
     DistributionId: ["E1ADYLIWRYAZZC"]
     Region: ["Global"]
 - aws_namespace: AWS/CloudFront
   aws_metric_name: TotalErrorRate
   aws_statistics: [Average]
   aws_dimensions: [DistributionId,Region]
   aws_dimension_select:
     DistributionId: ["E1ADYLIWRYAZZC"]
     Region: ["Global"]
 - aws_namespace: AWS/CloudFront
   aws_metric_name: Requests
   aws_statistics: [Sum]
   aws_dimensions: [DistributionId,Region]
   aws_dimension_select:
     DistributionId: ["E1ADYLIWRYAZZC"]
     Region: ["Global"]


启动命令(startup):
su ops -c '/apps/jdk/jdk-17.0.1/bin/java -jar /apps/exporter/cloudwatch_exporter-0.12.2-jar-with-dependencies.jar 9106 /apps/exporter/cloudwatch-metrics-p7-cdn.yml 1>/apps/exporter/cloudwatch-metrics-p7-cdn.log 2>&1 &'

```

#### Prometheus
```

配置文件(config files):
---# cat ./prometheus.yml
# my global config
global:
  scrape_interval: 60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 20s
  # scrape_timeout is set to the global default (10s).
  external_labels:
    ident: public
    project: public
    env: public
    app: ec2-prometheus

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "rules/*rules.yaml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

  ...
  - job_name: "yace"
    metrics_path: /metrics
    file_sd_configs:
    - files:
      - targets/yace.yaml
      refresh_interval: 10m

  - job_name: "cloudwatch-exporter"
    metrics_path: /metrics
    file_sd_configs:
    - files:
      - targets/cloudwatch-exporter.yaml
      refresh_interval: 10m

  ...


启动命令(startup):
su ops -c 'cd /apps/prometheus/prometheus && ./prometheus --web.enable-lifecycle --storage.tsdb.retention.time=15d --config.file=/apps/prometheus/prometheus/prometheus.yml 1>>/apps/prometheus/prometheus/logs 2>&1 &'


```

![cloudwatch-exporter](https://github.com/user-attachments/assets/7cf4ab2e-31d7-4a2e-8643-dd6e7f5a8d46)
![cloudwatch](https://github.com/user-attachments/assets/0f2b82b3-de08-48b6-9e46-353c29e15958)
![yace](https://github.com/user-attachments/assets/26ae7d06-1ea3-4f6a-9375-d25d68eaf80b)
