### ISSUE TITLE
AWS Shield DDoSDetected metric splitting to snakecase on change from upper to lowercase letter

### ISSUE THREAD

**Issue by AronNaylor** [prometheus/cloudwatch_exporter#769]
When splitting the AWS Shield Advanced DDoSDetected CloudWatch metric, it is incorrectly being parsed as follows due to the linked method:

```
region: us-east-1
metrics:
- aws_dimensions:
  aws_metric_name: DDoSDetected
  aws_namespace: AWS/DDoSProtection
  aws_statistics:
  - Sum
```

Becomes:

```
aws_ddosprotection_ddo_sdetected_sum
```

This occurs only when a lowercase letter appears in the middle of a word within a metric name which contains multiple words (see example above),  but not the namespace (see code refs below).

https://github.com/prometheus/cloudwatch_exporter/blob/68a84c7135d361880981877c02f85156ace7e47a/src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java#L427

https://github.com/prometheus/cloudwatch_exporter/blob/68a84c7135d361880981877c02f85156ace7e47a/src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java#L482
