### ISSUE TITLE
[metrics]: Add EBS volumes tags as labels of metrics

### ISSUE THREAD

**Issue by MrCirca** [prometheus/cloudwatch_exporter#777]
### Context information

* AWS service: EC2:volume
* CloudWatch namespace: AWS/EBS
* Link to metrics documentation for this service: https://docs.aws.amazon.com/ebs/latest/userguide/using_cloudwatch_ebs.html
* AWS region of the exporter: eu-central-1
* AWS region of the service: eu-central-1

<details>
    <summary>
        Exporter configuration
    </summary>

```yaml
- aws_namespace: AWS/EBS
    aws_metric_name: VolumeReadOps
    aws_dimensions: [VolumeId]
    aws_tag_select:
      resource_type_selection: "ec2:volume"



```

</details>

<details>
    <summary>
        Exporter logs
    </summary>

```log

```
</details>

### What do you expect to happen?

I retrieve AWS EBS volume metrics using the Prometheus CloudWatch Exporter. Each EBS volume has associated tags, one of which is the node or pod name to which it is attached. I am a solution to create labels based with the tag values. I tried using tag_selection and similar configurations, but nothing seems to work. Cloudwatch exporter lives in a pod
### What happened instead?
Nothing. No labels added.
