### ISSUE TITLE
Scraping fails when trying to scrape a certain metric from more then one target of the same type

### ISSUE THREAD

**Issue by eranreshef** [prometheus/cloudwatch_exporter#79]
I'm trying to use the cloudwatch exporter in order to monitor several ec2 instances that are divided to 2 logic groups. 
The cloudwatch configuration looks something like this:
```
...
...
# EC2 group 1
- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_dimension_select:
   InstanceId: [i-X, i-Y, i-Z]
...
...
# EC2 group 2
- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_dimension_select:
   InstanceId: [i-A, i-B, i-C]
```

After starting the container and looking at the prometheus I get the following error:

> format parsing error in line xxx: second HELP line for metric name "aws_ec2_cpuutilization_sum"

 and indeed the scraped data has 2 HELP lines per metric.

Shouldn't the exporter merge the 2 metrics to same area in the scraped data and have a single help line for the block?

Thanks!

**Comment by brian-brazil** [comment]
This is expected, you need to reference a given metric only once.

**Comment by eranreshef** [comment]
changing my config to:
```
...
...
# EC2 group 1
- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_dimension_select:
   InstanceId: [i-X, i-Y, i-Z, i-A, i-B, i-C]
...
...
```
will cause the exporter to collect the exact same metrics as the configuration above but with only one HELP line. So it will solve the problem for the prometheus parser but will make my configuration less understandable and intuitive. So why not fix the cloudwatch exporter to merge all metrics from same type to one block with one HELP line?

**Comment by brian-brazil** [comment]
That's not quite in line with how metrics work with Prometheus, and when you're getting to selecting specific instances I'd presume you've configuration management in place to handle this.

**Comment by eranreshef** [comment]
well its actually a jinja2 template thats being rendered by some automatic tool, so until this issue is fixed (hopefully) I'll need to change my template from:
```
...
...
# EC2 group 1
- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_dimension_select:
   InstanceId: {{ instances_list_1}}
...
...
# EC2 group 2
- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_dimension_select:
   InstanceId: {{ instances_list_2}}
```
to:
```
# EC2 group 1+2
- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId]
  aws_dimension_select:
   InstanceId: {{ instances_list_1 + instances_list_2 }}
```
