### ISSUE TITLE
[metrics]: ignoring metric AWS/SNS <any> due to dimensions mismatch

### ISSUE THREAD

**Issue by matsonkepson** [prometheus/cloudwatch_exporter#794]
### Context information

* AWS service: SNS
* CloudWatch namespace: AWS/SNS
* Link to metrics documentation for this service: https://docs.aws.amazon.com/sns/latest/dg/sns-monitoring-using-cloudwatch.html#sns-metric-dimensions
* AWS region of the exporter: eu-central-1
* AWS region of the service: eu-central-1
* Agent version: 0.16.0
* AWS Api Metrics : GetMetricData

<details>
    <summary>
        Exporter configuration
    </summary>

### Config before templating
```yaml
<snip...>
    sns:
      enabled: true
      aws_namespace: "AWS/SNS"
      aws_dimension_select_regex:
        TopicName: ["mytopicx.*"]
      aws_tag_select:
        resource_type_selection: "sns:topic"
        resource_id_dimension: "TopicName"
      metrics:
        - aws_metric_name: NumberOfMessagesPublished
          aws_dimensions: [TopicName]
          aws_statistics: [Sum]
        - aws_metric_name: NumberOfNotificationsDelivered
          aws_dimensions: [TopicName]
          aws_statistics: [Sum]
        - aws_metric_name: PublishSize
          aws_dimensions: [TopicName]
          aws_statistics: [Average]
        - aws_metric_name: NumberOfNotificationsFailed
          aws_dimensions: [TopicName]
          aws_statistics: [Sum]

```
### Config after templating inside ConfigMap, config.yml

```yaml
        - aws_namespace: AWS/SNS
          aws_metric_name: NumberOfMessagesPublished
          aws_dimensions:
            - TopicName
          aws_statistics:
            - Sum
          aws_tag_select:
            resource_type_selection: "sns:topic"
            resource_id_dimension: TopicName
          aws_dimension_select_regex:
              TopicName:
              - mytopicx.*
        - aws_namespace: AWS/SNS
          aws_metric_name: NumberOfNotificationsDelivered
          aws_dimensions:
            - TopicName
          aws_statistics:
            - Sum
          aws_tag_select:
            resource_type_selection: "sns:topic"
            resource_id_dimension: TopicName
          aws_dimension_select_regex:
              TopicName:
              - mytopicx.*
        - aws_namespace: AWS/SNS
          aws_metric_name: PublishSize
          aws_dimensions:
            - TopicName
          aws_statistics:
            - Average
          aws_tag_select:
            resource_type_selection: "sns:topic"
            resource_id_dimension: TopicName
          aws_dimension_select_regex:
              TopicName:
              - mytopicx.*
        - aws_namespace: AWS/SNS
          aws_metric_name: NumberOfNotificationsFailed
          aws_dimensions:
            - TopicName
          aws_statistics:
            - Sum
          aws_tag_select:
            resource_type_selection: "sns:topic"
            resource_id_dimension: TopicName
          aws_dimension_select_regex:
              TopicName:
              - mytopicx.*
```
</details>

<details>
    <summary>
        Exporter logs
    </summary>

```log
Feb 05, 2025 8:04:51 AM io.prometheus.cloudwatch.DefaultDimensionSource listDimensions
WARNING: (listDimensions) ignoring metric AWS/SNS:NumberOfMessagesPublished due to dimensions mismatch
Feb 05, 2025 8:04:52 AM io.prometheus.cloudwatch.DefaultDimensionSource listDimensions
WARNING: (listDimensions) ignoring metric AWS/SNS:NumberOfNotificationsDelivered due to dimensions mismatch
Feb 05, 2025 8:04:52 AM io.prometheus.cloudwatch.DefaultDimensionSource listDimensions
WARNING: (listDimensions) ignoring metric AWS/SNS:PublishSize due to dimensions mismatch
Feb 05, 2025 8:04:52 AM io.prometheus.cloudwatch.DefaultDimensionSource listDimensions
WARNING: (listDimensions) ignoring metric AWS/SNS:NumberOfNotificationsFailed due to dimensions mismatch
```

### What do you expect to happen?

Metrics are getting scraped or no Warning is shown

### What happened instead?

Instead I am getting warning logs inside pod

### Screen from CloudWatch web console 

![Image](https://github.com/user-attachments/assets/27023dcd-b7d7-4405-8fcc-80f96652471a)
