### ISSUE TITLE
[metrics]: ignoring metric AWS/Lambda DeadLetterErrors and UnreservedConcurrentExecutions due to dimensions mismatch

### ISSUE THREAD

**Issue by matsonkepson** [prometheus/cloudwatch_exporter#796]
### Context information

* AWS service: Lambda
* CloudWatch namespace: AWS/Lambda
* Link to metrics documentation for this service: https://docs.aws.amazon.com/lambda/latest/dg/monitoring-metrics-types.html
* AWS region of the exporter: eu-central-1
* AWS region of the service: eu-central-1
* Agent version: 0.16.0
* AWS Api Metrics : GetMetricData

<details>
    <summary>
        Exporter configuration
    </summary>

```yaml

        - aws_namespace: AWS/Lambda
          aws_metric_name: DeadLetterErrors
          aws_dimensions:
            - FunctionName
          aws_statistics:
            - Sum
          aws_tag_select:
            resource_type_selection: "lambda:function"
            resource_id_dimension: FunctionName
          aws_dimension_select_regex:
              FunctionName:
              - mylambdax.*
       - aws_namespace: AWS/Lambda
          aws_metric_name: UnreservedConcurrentExecutions
          aws_dimensions:
            - FunctionName
          aws_statistics:
            - Sum
          aws_tag_select:
            resource_type_selection: "lambda:function"
            resource_id_dimension: FunctionName
          aws_dimension_select_regex:
              FunctionName:
              - mylambdax.*

```

</details>

<details>
    <summary>
        Exporter logs
    </summary>

```log
Feb 07, 2025 2:06:53 PM io.prometheus.cloudwatch.DefaultDimensionSource listDimensions
WARNING: (listDimensions) ignoring metric AWS/Lambda:DeadLetterErrors due to dimensions mismatch
Feb 07, 2025 2:06:53 PM io.prometheus.cloudwatch.DefaultDimensionSource listDimensions
WARNING: (listDimensions) ignoring metric AWS/Lambda:UnreservedConcurrentExecutions due to dimensions mismatch
```

### What do you expect to happen?

Metrics are getting scraped or no Warning is shown

### What happened instead?

Instead I am getting warning logs inside pod

### Additional info
FYI
this is actually  same same whats here > https://github.com/prometheus/cloudwatch_exporter/issues/794
i am using same agent and crawling same AWS project
