### ISSUE TITLE
[Question] Exporting SQS metric

### ISSUE THREAD

**Issue by alok87** [prometheus/cloudwatch_exporter#82]
```
---
region: ap-south-1
metrics:
- aws_namespace: AWS/SQS
  aws_metric_name: ApproximateNumberOfMessagesVisible
  aws_dimensions: [QueueName]
  aws_statistics: [Average]
```
Deployed prometheus cloudwatch exporter in kubernetes using above config. I am trying to look for `aws_sqs_approximate_number_of_messages_visible_average` in the prometheus UI but it does not show there. 
The logs shows no errors and IAM permission are correctly configured. I am able to access metrics from aws cli

Please suggest how to debug the issue.
