### ISSUE TITLE
Support to specify prometheus metric name's prefix(used as basename in code)

### ISSUE THREAD

**Issue by alok87** [prometheus/cloudwatch_exporter#83]
Currently the exporter by default creates the name of the prometheus metric. But there are use cases where in we want to specify the name of the metric that is being exported.

So our products have a lot of queues in S3, and for each product we want to run the exporter(not the central exporter) and configure it again as the new queues gets added. And also we want to name them our way for other use cases.

Support to specify `prometheus_metric_name_prefix`
```
---
region: eu-west-1
metrics:
 - prometheus_metric_name_prefix: aws_lb_{mylb}
   aws_namespace: AWS/ELB
   aws_metric_name: RequestCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [myLB]
   aws_statistics: [Sum]
```
This can be done using prometheus rules. But there are use cases which requires it to be handled in the exporter.

**Comment by brian-brazil** [comment]
That would be considered an anti-pattern in Prometheus, see https://www.robustperception.io/undoing-the-benefits-of-labels/

**Comment by alok87** [comment]
@brian-brazil This is an optional option and is required in some use cases. It is only a prefix change and the rest of the things can be same.

**Comment by alok87** [comment]
@brian-brazil how is the calls to the /metrics made from the config
I added the change is showing only one metric
```root@prometheus-cloudwatch-exporter-647bff675f-d2xnl:/# curl localhost:9106/metrics | grep aws
aws_sqsq_product_queue_1_sum{job="aws_sqs",instance="",queue_name="product-queue-1",} 5.0
```

**Comment by brian-brazil** [comment]
> This is an optional option and is required in some use cases. 

Can you explain the use case? Labels should be sufficient to distinguish the time series, and it's incorrect to prefix identical metrics in different deployments.

**Comment by alok87** [comment]
@brian-brazil We have say `n` products in an organization say `product_1`, `product_2`etc.. Each product is there in a separate namespace in kubernetes say `product_1`, product_2` etc..

Each product has a SQS queue say `product_1_queue_1`, `product_2_queue_3` in each namespace. We want to scale deployment `product_1_consumer_1` which watches `product_1_queue_1` in each namespace.

HPA configuration in kubernetes work by Service in the same namespace as HPA.
```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: product_1_consumer_1_scaler
  namespace: product_1
spec:
  scaleTargetRef:
    kind: Deployment
    name: product_1_consumer_1
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: product_1_consumer_1_exporter
      metricName: product_1_queue_1
      targetValue: 100
```
The above HPA will result in the Prometheus query `product_1_queue_1{service="product_1_consumer_1_exporter",namespace="product_1"}`

To make the above work we need the metric with a specific name.
