### ISSUE TITLE
Cloudfront metrics not being pulled

### ISSUE THREAD

**Issue by Mornor** [prometheus/cloudwatch_exporter#93]
I am trying to scrape Cloudfront metrics from AWS. 
From the [docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cf-metricscollected.html), the region must be set to `Global`. 

However, with the following configuration: 
```
region: Global
    metrics:
     - aws_namespace: AWS/CloudFront
       aws_metric_name: Requests
       aws_statistics: [Sum]
       aws_dimensions: [DistributionId]
```

The following error is thrown: 
```
Exception in thread "main" java.lang.NullPointerException
	at io.prometheus.cloudwatch.CloudWatchCollector.getMonitoringEndpoint(CloudWatchCollector.java:197)
	at io.prometheus.cloudwatch.CloudWatchCollector.loadConfig(CloudWatchCollector.java:128)
	at io.prometheus.cloudwatch.CloudWatchCollector.loadConfig(CloudWatchCollector.java:94)
	at io.prometheus.cloudwatch.CloudWatchCollector.&lt;init&gt;(CloudWatchCollector.java:72)
	at io.prometheus.cloudwatch.WebServer.main(WebServer.java:25)
```

Which does not appear when the region is set to `us-east-1` for example.

**Comment by brian-brazil** [comment]
There is no Global AWS region. You want aws_dimension_select.

**Comment by Mornor** [comment]
Per the AWS documentation: ["The region for which you want to display metrics. This value must be Global."](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cf-metricscollected.html) 
However, seems that using `us-east-1` also works [as described here](https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/issues/4)

**Comment by brian-brazil** [comment]
You're confusing the two different uses of region here.

**Comment by Mornor** [comment]
Also, even when using `us-east-1`, the metrics are not being pulled:
```
region: us-east-1
    metrics:
      - aws_namespace: AWS/CloudFront
         aws_metric_name: Requests
         aws_statistics: [Sum]
```

**Comment by Mornor** [comment]
I'd like to re-open this, as I still can't fetch Cloudfront metrics. 
My config file is as follow: 

```
region: us-east-1
metrics:
   - aws_namespace: WAF
     aws_metric_name: BlockedRequests
     aws_statistics: [Sum]

   - aws_namespace: AWS/Billing
     aws_dimensions: [Currency]
     aws_dimensions_select:
       Currency: [USD]
     aws_metric_name: EstimatedCharges
     aws_statistics: [Maximum]
     range_seconds: 86400

   - aws_namespace: AWS/CloudFront
     aws_metric_name: Requests
     aws_statistics: [Sum]
     aws_dimensions: [DistributionId]
```

But I only get the metrics from the Billing. No metrics from Cloudront or WAF.
