### ISSUE TITLE
Add optional support for ec2 / elb / rds / es filtering of tags and tag labels

### ISSUE THREAD

**Issue by thomaspeitz** [prometheus/cloudwatch_exporter#96]
Hey Ho,

i would like to implement filtering / target discovery based on tags for a small list of aws services. The tags would be added as prometheus labels as well.

Saw a closed issue (https://github.com/prometheus/cloudwatch_exporter/issues/20) where this statement where added - "By my count there are currently 41 AWS services (and that's just AWS services) providing data in Cloudwatch. We're not going to add every possible object field from those." - Personally i really love this project but we quite use it only for old static things which is sad. New things e.g. elbs managed by kubernetes are not monitorable with this project as ids change a lot (tags are the same). Even if we would write something which automatically generates a config for this project, the exported metrics would not help because of missing tag labels. Therefore i would like to start working on this problem.

There would be a 2nd option to implement this - Giving users the ability to add custom labels to exported metrics. Then we could write a sidecar app which just creates/manages the config file and reloads exporter on changes.

From my perspective i prefer option one as it allows users easy monitoring of aws resources without running a 2nd container.

I would start on of those two options as soon as i get your go!

Greetings, Thomas

**Comment by tsupertramp** [comment]
@brian-brazil - Even if i would monitor all elbs for example, tags would still be missing. So i only have the information of the ids. So how would you add tag labels for example or filter them on prometheus end? - Maybe i have an misunderstanding of the concept how to use prometheus? - Maybe you can help me? - But for me it seems something is missing. - By the way i see this as a problem on aws api side. AWS should add the tags on cloudwatch metrics side. Then it would be very easy to implement this.

**Comment by brian-brazil** [comment]
> So how would you add tag labels for example or filter them on prometheus end? 

I'd suggest a kube-state-metrics like exporter that exposed these labels.

> AWS should add the tags on cloudwatch metrics side.

Yes, that'd be a much better way to handle this.

**Comment by tsupertramp** [comment]
@brian-brazil - Ah i see you mean using kube-state-metrics like exporter and then use these metrics in a query to find the corresponding cloudwatch metrics. This could work on the downside this will lead to big queries in alerting rules and grafana. - Will think over you ideas and try to solve it somehow. - Thanks for your input! Really appreciate your work!

**Comment by brian-brazil** [comment]
I can't imagine you having the number of ELBs where that would be a problem, especially as your regular target scraping will be an issue well before that.

**Comment by mikhailadvani** [comment]
would it be an option to leverage the https://docs.aws.amazon.com/cli/latest/reference/resourcegroupstaggingapi/get-resources.html? It would not be most straightforward since some generic custom parsing of ARN to resourceId would be required.

Something like id = from ResourceARN.findLast(':' or '/') to last character.

Proposed usage in Cloudwatch Exporter Config:
- aws_namespace: AWS/EC2
  aws_metric_name: CPUCreditBalance
  aws_dimensions: [InstanceId]
  aws_tag_filter:
  - Key: Environment
     Values: ["Test", "Dev"]
  aws_statistics: [Average]

The aws_dimensions in this scenario needs to be only one field that should be the Identifier of the resource viz. the InstanceId(EC2) or BucketName(S3) or TunnelIpAddress (VPN).

thoughts?

**Comment by brian-brazil** [comment]
How exactly would you map between listMetrics and this call?

**Comment by brian-brazil** [comment]
How do you get from the getResources call to InstanceId=i-1234567890 ?

**Comment by mikhailadvani** [comment]
I tried a dry-run of the workflow and realised that there would be the need of another field as well. So the exporter config yaml will need:

```
metrics: 
  - aws_namespace: AWS/EC2
     aws_metric_name: CPUCreditBalance
     aws_dimensions: [InstanceId]
     aws_tag_filter:
        - Key: Environment
           Values: ["Test", "Dev"]
        - Key: Application
           Values: ["WebServer"]
     aws_arn_prefix: arn:aws:ec2
     aws_statistics: [Average]
```

Pseudo code of what would be executed:

1. taggingApiResponse = aws resourcegroupstaggingapi get-resources --tag-filters Key=Environment,Values=["Test", "Dev"] Key=Application,Values=["WebServer"]
2. resourceARNs = taggingApiResponse.ResourceTagMappingList.collect("ResourceARN")
3. Extract IDs from the ARNs  id = from ResourceARN.findLast(':' or '/').
4. Query Cloudwatch in the format which would be similar to the following which is already supported by cloudwatch_exporter

```
metrics: 
  - aws_namespace: AWS/EC2
     aws_metric_name: CPUCreditBalance
     aws_dimensions: [InstanceId]
     aws_dimension_select:
        InstanceId: [<ID_RETURNED_FROM_STEP3>]
     aws_statistics: [Average]
```

Though this is not the most elegant solution it is one that solves the problem

**Comment by brian-brazil** [comment]
What happens if there's aws_dimensions beyond the one from the tags?

**Comment by mikhailadvani** [comment]
the other option I think would be to have something like.

```
metrics: 
  - aws_namespace: AWS/EC2
    aws_metric_name: CPUCreditBalance
    aws_dimensions: [InstanceId]
    aws_dimension_tag_filters:
        - dimension_key: InstanceId
          filters:
            - Key: Environment
               Values: ["Test", "Dev"]
            - Key: Application
               Values: ["WebServer"]
    aws_arn_prefix: arn:aws:ec2
    aws_statistics: [Average]
```
